local TroopHUDSchema = {
    --Object
    {"facingCamera", typeof(CS.U2DFacingCameraECS) },
    {"hudAnimTrigger", typeof(CS.FpAnimation.FpAnimationCommonTrigger) },
    --SimpleInfo
    {"simpleInfoRoot",typeof(CS.UnityEngine.GameObject)},    
    {"iconGo",typeof(CS.UnityEngine.GameObject)},
    {"iconBaseImg",typeof(CS.U2DSpriteMesh)},
    {"iconImg",typeof(CS.U2DSpriteMesh)},
    {"monsterIconImg",typeof(CS.U2DSpriteMesh)},
    {"nameTxt",typeof(CS.U2DTextMesh)},
    {"hpGo",typeof(CS.UnityEngine.GameObject)},
    {"hpValueRect",typeof(CS.UnityEngine.RectTransform)},
    {"hpValueMiddleImg",typeof(CS.U2DSpriteMesh)},
    {"hpValueImg",typeof(CS.U2DSpriteMesh)},
    {"hpNormalColor",typeof(CS.UnityEngine.Color)},
    {"hpDeadlyColor",typeof(CS.UnityEngine.Color)},
    {"healAnimDelay",typeof(CS.System.Single)},
    {"healAnimDuration",typeof(CS.System.Single)},
    {"healAnimColor",typeof(CS.UnityEngine.Color)},
    {"hurtAnimDelay",typeof(CS.System.Single)},
    {"hurtAnimDuration",typeof(CS.System.Single)},
    {"hurtAnimColor",typeof(CS.UnityEngine.Color)},
    {"seriousAnimDelay",typeof(CS.System.Single)},
    {"seriousAnimDuration",typeof(CS.System.Single)},
    {"seriousAnimColor",typeof(CS.UnityEngine.Color)},
    {"hpValueText",typeof(CS.U2DTextMesh)},
    -- {"mpGo",typeof(CS.UnityEngine.GameObject)},
    -- {"maxMpAmount",typeof(CS.System.Single)},
    -- {"minMpAmount",typeof(CS.System.Single)},
    -- {"mpValueImg",typeof(CS.U2DSpriteMesh)},
    {"troopStateBack",typeof(CS.U2DSpriteMesh)},
    {"troopStateImg",typeof(CS.U2DSpriteMesh)},
    {"troopEscrowImg",typeof(CS.U2DSpriteMesh)},
    {"troopKindBaseGo",typeof(CS.UnityEngine.GameObject)},
    {"troopKindImg",typeof(CS.U2DSpriteMesh)},
    {"burstGo",typeof(CS.UnityEngine.GameObject)},
    {"burstTimer",typeof(CS.U2DSpriteMesh)},
    --detail info with 3 Heros 
    {"detailInfoRoot",typeof(CS.UnityEngine.GameObject)},
    --bottom lvl
    {"facingCamera_bottom", typeof(CS.U2DFacingCameraECS) },    
    {"lvGo_bottom", typeof(CS.UnityEngine.GameObject) },
    {"lvTxt_bottom",typeof(CS.U2DTextMesh)},
    {"lvBack_bottom",typeof(CS.U2DSpriteMesh)},
    {"monsterIcon", typeof(CS.U2DSpriteMesh)},
    {"monsterIconGo_bottom",typeof(CS.UnityEngine.GameObject)},
    {"radarTaskGo",typeof(CS.UnityEngine.GameObject)},
    {"radarTaskBase",typeof(CS.U2DSpriteMesh)},
    {"radarTaskIcon",typeof(CS.U2DSpriteMesh)},
    {"trigger", typeof(CS.DragonReborn.LuaBehaviour)},
    {"titleGo",typeof(CS.UnityEngine.GameObject)},
    {"textTitle",typeof(CS.U2DTextMesh)},
    {"imgIcon",typeof(CS.U2DSpriteMesh)},
    {"imgTitle_l",typeof(CS.U2DSpriteMesh)},
    {"imgTitle",typeof(CS.U2DSpriteMesh)},
    {"imgTitle_r",typeof(CS.U2DSpriteMesh)},
    {"eventIcon",typeof(CS.U2DSpriteMesh)},
    {"hammer",typeof(CS.UnityEngine.GameObject)},
}

return TroopHUDSchema