local MapTileView = require("MapTileView")
local PvPTileAssetVillage = require("PvPTileAssetVillage")
local PvPTileAssetHUDConstructionVillage = require("PvPTileAssetHUDConstructionVillage")
local PvPTileAssetHUDIconVillage = require("PvPTileAssetHUDIconVillage")
local PvPTileAssetProtectionShield = require("PvPTileAssetProtectionShield")
local PvPTileAssetHUDFighting = require("PvPTileAssetHUDFighting")
local PvPTileAssetVFXVillageBroken = require("PvPTileAssetVFXVillageBroken")
local PvPTileAssetVFXVillageOccupied = require("PvPTileAssetVFXVillageOccupied")
local PvPTileAssetHUDTroopHead = require("PvPTileAssetHUDTroopHead")
local PvPTileAssetVillageAllianceCenter = require("PvPTileAssetVillageAllianceCenter")
local PvPTileAssetVillageAllianceCenterUpgradingVfx = require("PvPTileAssetVillageAllianceCenterUpgradingVfx")
local PvPTileAssetUpgradeAllianceCenterCompleteVFX = require("PvPTileAssetUpgradeAllianceCenterCompleteVFX")
-- local PvPTileAssetHUDBeamRedVfx = require("PvPTileAssetHUDBeamRedVfx")
local PvPTileAssetVillageWarningBreath = require("PvPTileAssetVillageWarningBreath")
local PvPTileAssetVillageRadarBubble = require("PvPTileAssetVillageRadarBubble")
local PvPTileAssetVFXVillageRebuilding = require("PvPTileAssetVFXVillageRebuilding")

---@class PvPTileViewVillage : MapTileView
local PvPTileViewVillage = class("PvPTileViewVillage", MapTileView)

function PvPTileViewVillage:ctor()
    MapTileView.ctor(self)
    self:AddAsset(PvPTileAssetVillage.new())
    self:AddAsset(PvPTileAssetHUDConstructionVillage.new())
    self:AddAsset(PvPTileAssetHUDIconVillage.new())
    self:AddAsset(PvPTileAssetProtectionShield.new())
    self:AddAsset(PvPTileAssetHUDFighting.new())
    self:AddAsset(PvPTileAssetVFXVillageBroken.new())
    self:AddAsset(PvPTileAssetVFXVillageOccupied.new())
    self:AddAsset(PvPTileAssetHUDTroopHead.new())
    self:AddAsset(PvPTileAssetVillageAllianceCenter.new())
    self:AddAsset(PvPTileAssetVillageAllianceCenterUpgradingVfx.new())
    self:AddAsset(PvPTileAssetUpgradeAllianceCenterCompleteVFX.new())
    --self:AddAsset(PvPTileAssetVillageWarningBreath.new())
    self:AddAsset(PvPTileAssetVillageRadarBubble.new())
    self:AddAsset(PvPTileAssetVFXVillageRebuilding.new())
    -- 攻占时特效
    -- self:AddAsset(PvPTileAssetHUDBeamRedVfx.new())
end

return PvPTileViewVillage
