local ModuleRefer = require("ModuleRefer")
local BattlePassConst = {
    TASK_TAB_TYPE = {
        DAILY = 1,
        WEEKLY = 2,
        SEASON = 3,
    },
    NORMAL_BP_ID = 1,
    NORMAL_BP_ACT_ID = 5,
    TASK_TAB_NAME_I18NKEY = {
        [1] = "battlepass_task_daily_title",
        [2] = "battlepass_task_week_title",
        [3] = "battlepass_task_season_title",
    },
    REWARD_STATUS = {
        LOCKED = 1,
        UNCLAIMABLE = 2,
        CLAIMABLE = 3,
        CLAIMED = 4,
    },
    REWARD_CLAIM_TYPE = {
        NORMAL = 1,
        ADV = 2,
        ALL = 3,
    },
    SYS_ENTRY_ID = 32,
    NOTIFY_NAMES = {
        ENTRY = "BattlePassEntry",
        REWARD = "BattlePassReward",
        TASK = "BattlePassTask_",
    },
    I18N_KEYS = {
        HUD = "battlepass_hub_name",
        TITLE = "battlepass_title",
        REMAIN_TIME_TXT = "battlepass_remain_time_txt",
        REMAIN_TIME = "battlepass_remain_time",
        REMAIN_TIME_D_H = "battlepass_remain_time",
        REMAIN_TIME_H_M = "battlepass_remain_time_1",
        BASIC_NAME = "battlepass_basic_name",
        SENIOR_NAME = "battlepass_senior_name",
        WEEKLY_LIMIT = "battlepass_point_weekly_limit",
        BUY_LVL = "battlepass_buy_level_btn_txt",
        BUY_LVL_DESC = "battlepass_buy_level_hint_desc",
        BUY_LVL_PAY_TXT = "battlepass_buy_level_hint_pay_txt",
        BUY_LVL_CONFIRM = "battlepass_buy_level_hint_confirm",
        LVL_UP = "battlepass_levelup_txt",
        TAB_TASK_TITLE = "battlepass_tab_task_title",
        TAB_REWARD_TITLE = "battlepass_tab_reward_title",
        CLAIM_ALL = "battlepass_tab_all_claim_btn_title",
        LVL_MAX = "battlepass_fulllevel_txt",
        LVL_MAX_TIPS = "battlepass_fulllevel_tips",
        DAILY_TASK_TITLE = "battlepass_task_daily_title",
        WEEKLY_TASK_TITLE = "battlepass_task_week_title",
        SEASON_TASK_TITLE = "battlepass_task_season_title",
        TASK_GOTO = "battlepass_task_goto",
        TASK_CLAIM = "battlepass_task_claim",
        PAY_BTN = "battlepass_pay_btn_txt",
        PAY_SENIOR_TITLE = "battlepass_pay_hint_senior_title",
        PAT_SENIOR_SUBTITLE = "battlepass_pay_hint_senior_subtitle",
        PAY_SUPER_TITLE = "battlepass_pay_hint_surper_title",
        PAY_SUPER_DESC1 = "battlepass_pay_hint_surper_desc1",
        PAY_SUPER_DESC2 = "battlepass_pay_hint_surper_desc2",
        PAY_SUPER_SUBTITLE = "battlepass_pay_hint_surper_subtitle",
        PAY_BTN_TXT = "battlepass_pay_hint_buy_btn",
        PAY_SOLD_OUT = "battlepass_pay_hint_sold_btn",
        PAY_HINT = "battlepass_pay_hint_txt",
        PAY_UNLOCKED_REWARDS = "battle_pass_show_all_reward",
        SUPER_NAME = "battlepass_surper_name",
        SUPER_MAKEUP_NAME = "battlepass_surper_makeup_name",
        SENIOR_DESC = "battlepass_senior_desc",
        SUPER_DESC = "battlepass_senior_desc",
        SUPER_MAKEUP_DESC = "battlepass_surper_makeup_desc",
        CONTINUE_CLAIM = "battle_pass_continue_claim",
    },
}

return BattlePassConst