---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shoufeng.zhang.
--- DateTime: 2022/4/28 17:49
---
---@class LoadingSteps
local LoadingSteps = {
    --[]路径编号 [][]并行分支迁出自主路径第n步 [][]步骤编号
    --例如:10001代表主路径第2步; 20400代表主路径第5步迁出的分支第1步

    InitManifestState = 10000, -- 加载服务器配置 manifest
    IntroMovieState = 10001, -- 播放开场动画

    PrepareAssetState = 20000,  -- 下载loading资源
    SyncLanguagesState = 20003, -- 更新多语言
    SyncLuacState = 20001,      -- 更新luac
    SyncConfigsState = 20002,   -- 更新配置
    SyncAudioState = 20004,     -- 更新音频
    SyncKingdomDataState = 20005, -- 更新Kingdom数据
    SyncAssetBundlesState = 20006, -- 更新AssetBundle

    PreInitDataState = 30000,   -- 登录前
    InitDataState = 30001,      -- 登录
    PostInitDataState = 30002,  -- 登录后

    WarmUpState = 40000,        -- warmup

    PreloadingEndState = 50000, -- loading结束

    SceneLoadedState = 60000,   -- 场景加载完成


    -- PrepareAssetState = 10001, -- 准备一部分资源
    -- MigrateState = 10002, -- 迁移账号(mycard包的需求)
    -- AccountState = 10003, -- 连接账号服务器
    -- GreyPublishState = 10004, -- 灰度发布
    -- PrivacyState = 10005, -- 通用的隐私条款（SDK提供）
    -- CheckUserState = 10006, -- 判断是否为新用户
    -- CheckAllowNewUser = 10007, -- 检测是否允许新用户进入(渠道需求)
    -- CheckInviteCodeState = 10008, -- 校验邀请码（某些渠道的新用户）
    -- InitDataState = 10009, -- 连接服务器 call init
    -- EuropeState = 10010, -- 欧盟隐私条款
    -- IntroMovieState = 10011, -- 开场视频
    -- CinemaA1State = 10012, -- 第一段新手剧情
    -- CinemaA2State = 10013, -- 第二段新手剧情
    -- CinemaBState = 10014, -- 第三段新手剧情
    -- SyncLoaderState = 10015, -- 连接服务器请求进游戏前数据
    -- PreloadingEndState = 10016, -- Loading 结束

    -- SyncConfigsState = 20400, -- 更新配置文件
    -- ParseConfigsState = 20401, -- 解析配置文件
    -- PreparePaymentState = 20402, -- 初始化支付模块

    -- SyncAssetBundleState = 30200, -- 更新 bundle 资源
    -- SyncLanguagesState = 40900, -- 更新多语言

    -- PrepareOtaState = 60900, -- 检查进入游戏前需要更新的bundle 资源
    -- WarmUpAssetState = 60901, --预热city和kingdom的资源
}

return LoadingSteps