---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yingjie.cui.
--- DateTime: 2022/8/19 20:25
---

---@class TaskManager
---@field new fun():TaskManager
local TaskManager = class("TaskManager", require("BaseManager"))

local Delegate = require('Delegate')

function TaskManager:ctor()
    self.manager = CS.DragonReborn.TaskManager.Instance;
    self.manager:OnGameInitialize(nil)
    g_Game:AddSystemTicker(Delegate.GetOrCreate(self,self.Tick))
end

function TaskManager:Reset()
    try_catch_traceback_with_vararg(self.manager.Reset, nil, self.manager)
    g_Game:RemoveSystemTicker(Delegate.GetOrCreate(self,self.Tick))
end

function TaskManager:OnLowMemory()
    try_catch_traceback_with_vararg(self.manager.OnLowMemory, nil, self.manager)
end

function TaskManager:Tick(delta)
    self.manager:Tick(delta)
end

return TaskManager