---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yingjie.cui.
--- DateTime: 2022/8/19 20:25
---

local Delegate = require('Delegate')

---@class VisualEffectManager
---@field new fun():VisualEffectManager
local VisualEffectManager = class("VisualEffectManager", require("BaseManager"))

function VisualEffectManager:ctor()
    self.manager = CS.DragonReborn.VisualEffect.VisualEffectManager.Instance;
    self.manager:OnGameInitialize(nil)
    g_Game:AddSystemTicker(Delegate.GetOrCreate(self,self.Tick))
end

function VisualEffectManager:Tick(delta)
    self.manager:Tick(delta)
end

function VisualEffectManager:Reset()
    try_catch_traceback_with_vararg(self.manager.Reset, nil, self.manager)
    g_Game:RemoveSystemTicker(Delegate.GetOrCreate(self,self.Tick))
end

function VisualEffectManager:OnLowMemory()
    try_catch_traceback_with_vararg(self.manager.OnLowMemory, nil, self.manager)
end

return VisualEffectManager