---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wupei.
--- DateTime: 2020/9/27
---

ColorUtil = sealedClass('ColorUtil')

---@return UnityEngine.Color
function ColorUtil.FromInt(r, g, b, a)
    a = a or 255
    return CS.UnityEngine.Color(r / 255, g / 255, b / 255, a / 255)
end

---@return UnityEngine.Color
function ColorUtil.FromHexNoAlpha(hex)
    local b = hex % 0x100
    local g = math.floor(hex / 0x100) % 0x100
    local r = math.floor(hex / 0x10000)
    return CS.UnityEngine.Color(r / 255, g / 255, b / 255, 1)
end

---@return UnityEngine.Color
function ColorUtil.FromHex(hex)
    local a = hex % 0x100
    local b = math.floor(hex / 0x100) % 0x100
    local g = math.floor(hex / 0x10000) % 0x100
    local r = math.floor(hex / 0x1000000) % 0x100
    return CS.UnityEngine.Color(r / 255, g / 255, b / 255, a / 255)
end

---@return UnityEngine.Color
function ColorUtil.FromHexString(hex)
    local num = tonumber(hex, 16)
    if num == nil then
        g_Logger.Error("ColorUtil.FromHexString() error. hex = %s", hex)
        num = 0xffffffff
    end
    return ColorUtil.FromHex(num)
end

---@return UnityEngine.Color
function ColorUtil.FromHexNoAlphaString(hex)
    local num = tonumber(hex, 16)
    if num == nil then
        g_Logger.Error("ColorUtil.FromHexNoAlphaString() error. hex = %s", hex)
        num = 0xffffff
    end
    return ColorUtil.FromHexNoAlpha(num)
end

---@param color32 Color32
---@return UnityEngine.Color
function ColorUtil.FromColor32Cfg(color32)
    local r = math.clamp(color32:R(), 0, 255) / 255
    local g = math.clamp(color32:G(), 0, 255) / 255
    local b = math.clamp(color32:B(), 0, 255) / 255
    local a = math.clamp(color32:A(), 0, 255) / 255
    return CS.UnityEngine.Color(r, g, b, a)
end

---@return string
function ColorUtil.FromGammaStrToLinearStr(linearHexStr)
    local success,color = CS.UnityEngine.ColorUtility.TryParseHtmlString(linearHexStr)
    if success then
        return '#' .. CS.UnityEngine.ColorUtility.ToHtmlStringRGBA(color.linear)
    end
    return "#ffffffff"
end

return ColorUtil
