local ManualResourceConst = {
    ui3d_root = 'ui3d_root',
    ui3d_bubble_radar = 'ui3d_bubble_radar',
    ui3d_bubble_progress = 'ui3d_bubble_progress',
    ui3d_hud_troop_lod = 'ui3d_hud_troop_lod',
    ui3d_bubble_building_repaired = 'ui3d_bubble_building_repaired',
    ui3d_world_battle = 'ui3d_world_battle',
    ui3d_bubble_btn = 'ui3d_bubble_btn',

    ui_hud_city_vfx_word_event_trail = 'ui_hud_city_vfx_word_event_trail',

    city_map_affair_selector = 'city_map_affair_selector',

    slg_world_config = 'slg_world_config',

    map_creep_selector = 'map_creep_selector',
    mask_circle = 'mask_circle',
    mat_kingdom_fog_plane = 'mat_kingdom_fog_plane',

    grid_map_system = 'grid_map_system',

    prefab_test_world_event_circle_complete = 'prefab_test_world_event_circle_complete',

    kingdom_placer = 'kingdom_placer',

    HexGridPerimeter = 'HexGridPerimeter',
    ui3d_district_names = 'ui3d_district_names',
    

    mdl_landform_root = 'mdl_landform_root',
    mdl_map_ocean_symbol = 'mdl_map_ocean_symbol',

    vfx_w_savation_pen = "vfx_w_savation_pen",
    vfx_w_world_event_circle_complete_yellow = 'vfx_w_world_event_circle_complete_yellow',

    --雷达
    sp_radar_img_frame_01 = 'sp_radar_img_frame_01',
    sp_radar_img_frame_02 = 'sp_radar_img_frame_02',
    sp_radar_img_frame_03 = 'sp_radar_img_frame_03',

    --雷达特效
    vfx_bigmap_leidakuosan = 'vfx_bigmap_leidakuosan',

    vx_ui_touch_feedback_01 = 'vx_ui_touch_feedback_01',
    vfx_bigmap_guangzhu_ground_green = 'vfx_bigmap_guangzhu_ground_green',
    vfx_bingmap_leida = 'vfx_bingmap_leida',
    vfx_bigmap_shenmishijian = 'vfx_bigmap_shenmishijian',
    vfx_bigmap_shenmishijian_ring = 'vfx_bigmap_shenmishijian_ring',
    vfx_common_base_accomplish = 'vfx_common_base_accomplish',
    vfx_w_bigmap_fighting = 'vfx_w_bigmap_fighting',
    vfx_bigmap_cloud_01 = 'vfx_bigmap_cloud_01',
    vfx_city_xiaosha_xishou = 'vfx_city_xiaosha_xishou',
    vfx_city_tileselected = 'vfx_city_tileselected',
    vfx_common_build_repair = 'vfx_common_build_repair',
    vfx_common_build_sweep = 'vfx_common_build_sweep',
    vfx_common_build_sweep_01 = 'vfx_common_build_sweep_01',
    vfx_w_common_build_clear_01 = 'vfx_w_common_build_clear_01',
    vfx_w_common_build_clear_01_2 = 'vfx_w_common_build_clear_01_2',
    vfx_w_common_build_clear_01_3 = 'vfx_w_common_build_clear_01_3',
    vfx_common_build_Box_01 = 'vfx_common_build_Box_01',
    fx_city_cloud_clear = 'fx_city_cloud_clear',
    vfx_w_bigmap_cai_ji = 'vfx_w_bigmap_cai_ji',
    vfx_city_gaibianfangjianleixing_9_12 = 'vfx_city_gaibianfangjianleixing_9-12',
    vfx_city_gaibianfangjianleixing_12_15 = 'vfx_city_gaibianfangjianleixing_12-15',
    vfx_city_gaibianfangjianleixing_15_18 = 'vfx_city_gaibianfangjianleixing_15-18',
    vfx_bigmap_jushoulichang_01 = "vfx_bigmap_jushoulichang_01",
    vfx_bigmap_behemoth_cage_entry_pos = "vfx_bigmap_behemoth_cage_entry_pos",
    fx_map_creep_line = "fx_map_creep_line",
    fx_zhongdu = "fx_zhongdu",
    fx_building_broken = "fx_building_broken",
    fx_city_dikuaixuanzhong2shansuo = "fx_city_dikuaixuanzhong2shansuo",
    fx_city_dikuaixuanzhong3changtai = "fx_city_dikuaixuanzhong3changtai",
    mdl_b_base_01_lod02 = "mdl_b_base_01_lod02",
    vfx_common_base_process = "vfx_common_base_process",
    mdl_world_uibridge_02 = "mdl_world_uibridge_02",
    mdl_world_uientrance_01 = "mdl_world_uientrance_01",
    vfx_bigmap_guangzhu_green_self = "vfx_bigmap_guangzhu_green_self",
    vfx_bigmap_guangzhu_red_attack = "vfx_bigmap_guangzhu_red_attack",
    vfx_bigmap_city_platyer_LOOP = "vfx_bigmap_city_platyer_LOOP",
    vfx_S_slg_city_bron = "vfx_S_slg_city_bron",
    vfx_bigmap_xiaoshatongzhiwu01 = "vfx_bigmap_xiaoshatongzhiwu01",
    vfx_s_city_building_lvup = "vfx_s_city_building_lvup",
    ui3d_progress_territory = "ui3d_progress_territory",
    ui3d_bubble_world_events = "ui3d_bubble_world_events",
    ui3d_building = "ui3d_building",
    ui3d_bubble_map_progress = "ui3d_bubble_map_progress",
    ui3d_bubble_building_icon = "ui3d_bubble_building_icon",
    ui3d_world_defence_troop = "ui3d_world_defence_troop",
    ui3d_bubble_map_popup_imagewithtext = "ui3d_bubble_map_popup_imagewithtext",
    fx_bigmap_pet_buzuo_01 = "fx_bigmap_pet_buzuo_01",
    vfx_bigmap_pet_baohuzhao = "vfx_bigmap_pet_baohuzhao",
    ui3d_bubble_world_ecs = "ui3d_bubble_world_ecs",
    behemoth_device_container = "behemoth_device_container",
    prefab_test_defense_tower_circle = "prefab_test_defense_tower_circle",
    WarnDecal = "WarnDecal",
    prefab_test_world_event_circle = "prefab_test_world_event_circle",
    ui3d_league_mark = "ui3d_league_mark",

    ui3d_progress_building = "ui3d_progress_building",
    vfx_common_build_Box_02 = "vfx_common_build_Box_02",
    ui3d_bubble_need = "ui3d_bubble_need",
    ui3d_progress_city = "ui3d_progress_city",
    ui3d_bubble_entrance_building = "ui3d_bubble_entrance_building",
    ui3d_tips_building = "ui3d_tips_building",
    vfx_w_common_city_jiaju_building = "vfx_w_common_city_jiaju_building",
    ui3d_bubble_group = "ui3d_bubble_group",
    ui3d_bubble_group_fog = "ui3d_bubble_group_fog",
    ui3d_bubble_group_hero_rescue = "ui3d_bubble_group_hero_rescue",
    ui3d_bubble_room_formula = "ui3d_bubble_room_formula",
    ui3d_name_city = "ui3d_name_city",
    ui3d_bubble_training = "ui3d_bubble_training",
    ui3d_bubble_gacha = "ui3d_bubble_draw",

    city_root = "city_root",
    city_map_grid = "city_map_grid",
    city_fog_root = "city_fog_root",
    city_creep_root = "city_creep_root",
    city_safe_area_wall_root = "city_safe_area_wall_root",
    ui3d_bubble_citizen_tip = "ui3d_bubble_citizen_tip",
    city_map_building_selector = "city_map_building_selector",
    city_map_creep_sweeper_selector = "city_map_creep_sweeper_selector",
    ui3d_bubble_risident_quantity = "ui3d_bubble_risident_quantity",
    city_room_floors = "city_room_floors",
    city_room_wall_and_door = "city_room_wall_and_door",
    mdl_city_crop_combine = "mdl_city_crop_combine",
    ui3d_bubble_default = "ui3d_bubble_default",
    ui3d_bubble_finish = "ui3d_bubble_finish",
    city_npc_capsule_city_trigger = "city_npc_capsule_city_trigger",
    city_npc_box_city_trigger = "city_npc_box_city_trigger",
    vfx_w_common_wall_loop_yellow = "vfx_w_common_wall_loop_yellow",
    vfx_w_common_wall_loop_green = "vfx_w_common_wall_loop_green",
    vfx_w_common_wall_top_yellow = "vfx_w_common_wall_top_yellow",
    vfx_w_common_wall_top_green = "vfx_w_common_wall_top_green",
    ui3d_bubble_interact = "ui3d_bubble_interact",
    city_bubble_citizen_work_progress = "city_bubble_citizen_work_progress",
    ui3d_science_zzz = "ui3d_science_zzz",
    vfx_bigmap_juntangbaozha = "vfx_bigmap_juntangbaozha",
    vfx_bigmap_city_hudun_LOOP = "vfx_bigmap_city_hudun_LOOP",
    vfx_bigmap_city_zhaohuo_03 = "vfx_bigmap_city_zhaohuo_03",
    vfx_bigmap_city_zhaohuo_02 = "vfx_bigmap_city_zhaohuo_02",
    vfx_bigmap_city_zhaohuo_01 = "vfx_bigmap_city_zhaohuo_01",
    vfx_bigmap_city_hudun_start = "vfx_bigmap_city_hudun_start",
    ui3d_bubble_timeline_npc_talk = "ui3d_bubble_timeline_npc_talk",
    mdl_city_levelup_01 = "mdl_city_levelup_01",
    cityData = "cityData",

    citySafeAreaSlice = "citySafeAreaSlice",
    cityWallSlice = "cityWallSlice",
    citySafeAreaEdge = "citySafeAreaEdge",
    cityZoneSlice = "cityZoneSlice",
    vfx_w_cai_ji_wu = "vfx_w_cai_ji_wu",
    city_camera_settings = "city_camera_settings",

    ui3d_bubble_egg = "ui3d_bubble_egg",
    ui3d_model_coastalForest = "ui3d_model_coastalForest",
    ui3d_toast_city_buff = "ui3d_toast_city_buff",

    --Slg战斗
    troop_skill = "troop_skill",
    SLGSketch = "SLGSketch",
    mat_troopline = "mat_troopline",
    mat_troopline_arrow = "mat_troopline_arrow",
    slg_floating_text_normal = "slg_floating_text_normal",
    slg_floating_text_number = "slg_floating_text_number",
    slg_floating_text_normal_critical = "slg_floating_text_normal_critical",
    slg_floating_text_debuff = "slg_floating_text_debuff",
    slg_floating_text_buff = "slg_floating_text_buff",
    slg_floating_text_healing = "slg_floating_text_healing",
    slg_floating_text_skillname = "slg_floating_text_skillname",
    slg_troop_status_start = "slg_troop_status_start",
    slg_troop_status_win = "slg_troop_status_win",
    slg_troop_status_fail = "slg_troop_status_fail",
    slg_floating_text_normal_city = "slg_floating_text_normal_city",
    troop_aim_fx = "troop_aim_fx",
    sp_custom_loading_icon_raw = "sp_custom_loading_icon_raw",

    ui3d_bubble_map_resource_field_status = "ui3d_bubble_map_resource_field_status",
    troop_map_resources = "troop_map_resources",

    vfx_w_caiji_born = "vfx_w_caiji_born",
    vfx_w_jing_ling_qiu_catch = "vfx_w_jing_ling_qiu_catch",
    mat_vfx_w_pet_catch_body = "mat_vfx_w_pet_catch_body",
    vfx_w_city_clean_lz = "vfx_w_city_clean_lz",
    city_team_city_trigger = "city_team_city_trigger",

    mdl_pilewood_01 = "mdl_pilewood_01",
    mdl_metalblock_01 = "mdl_metalblock_01",
    vfx_w_jing_ling_qiu_catch2 = "vfx_w_jing_ling_qiu_catch2",
    vfx_w_jing_ling_qiu_out = "vfx_w_jing_ling_qiu_out",

    sp_common_icon_time_01 = "sp_common_icon_time_01",
    sp_comp_icon_mark_hammer = "sp_comp_icon_mark_hammer",
    sp_comp_icon_build = "sp_comp_icon_build",

    ui3d_bubble_pet_status = "ui3d_bubble_pet_status",
    vfx_w_banyun = "vfx_w_banyun",

    sp_troop_icon_status_battle = "sp_troop_icon_status_battle",
    sp_troop_img_state_collect = "sp_troop_img_state_collect",
    sp_troop_img_state_base_1 = "sp_troop_img_state_base_1",
    sp_troop_img_state_base_2 = "sp_troop_img_state_base_2",
    sp_troop_img_state_base_3 = "sp_troop_img_state_base_3",
    sp_troop_img_state_base_4 = "sp_troop_img_state_base_4",

    vfx_w_slg_building = "vfx_w_slg_building",

    vfx_w_team_range = "vfx_w_team_range",
    
    se_jump_scene = "Assets/__Scene/_Resources/JumpScene/jump_scene_00.unity",
}

return ManualResourceConst