local ManualUIConst = {
    sp_world_base_3 = 'sp_world_base_3',
    sp_icon_lod_world_base_3 = 'sp_icon_lod_world_base_3',
    sp_comp_base_lv_village = 'sp_comp_base_lv_village',
    sp_radar_icon_worldevent_multi = 'sp_radar_icon_worldevent_multi',
    sp_base_world_event_toast_3 = 'sp_base_world_event_toast_3',
    sp_base_world_event_toast_4 = 'sp_base_world_event_toast_4',
    sp_comp_icon_worldevent = 'sp_comp_icon_worldevent',
    sp_base_world_event_toast_2 = 'sp_base_world_event_toast_2',
    sp_radar_icon_worldevent = 'sp_radar_icon_worldevent',
    sp_radar_icon_worldevent_league = 'sp_radar_icon_worldevent_league',
    sp_world_base_2 = 'sp_world_base_2',
    sp_icon_lod_world_base_4 = 'sp_icon_lod_world_base_4',
    sp_icon_lod_world_base_2 = 'sp_icon_lod_world_base_2',
    sp_comp_icon_worldevent_multi = 'sp_comp_icon_worldevent_multi',
    sp_item_slg_home = 'sp_item_slg_home',
    sp_world_base_4 = 'sp_world_base_4',
    sp_comp_icon_worldevent_league = 'sp_comp_icon_worldevent_league',
    sp_comp_base_lv_3 = 'sp_comp_base_lv_3',
    sp_mission_icon_recomment = 'sp_mission_icon_recomment',
    sp_common_base_black = 'sp_common_base_black',
    sp_white_solid = 'sp_white_solid',
    sp_common_icon_strong_2_star = 'sp_common_icon_strong_2_star',
    sp_common_icon_strong_3_star = 'sp_common_icon_strong_3_star',
    sp_common_icon_strong_4_star = 'sp_common_icon_strong_4_star',
    sp_common_icon_strong_5_star = 'sp_common_icon_strong_5_star',
    sp_common_base_bar_m = 'sp_common_base_bar_m',

}
return ManualUIConst