---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wupei.
--- DateTime: 2021/6/27
---

---@class SkillClientNative
local SkillClientNative = class("SkillClientNative")

local Vector3 = CS.UnityEngine.Vector3

---@param self SkillClientNative
---@param timer any
---@return void
function SkillClientNative:ctor(timer)
    self._timer = timer
end

---@param self SkillClientNative
---@param dataShake skillclient.data.CameraShake
---@return void
function SkillClientNative:CameraShake(dataShake)

end

---弹出伤害数字
---@param self SkillClientNative
---@param damageTextData any
---@param skillTarget any
---@param serverData any
---@return void
function SkillClientNative:SpawnDamageNum(damageTextData, skillTarget, serverData)

end

---@param self SkillClientNative
---@param offsetType any
---@return void
function SkillClientNative:GetOffset(offsetType)
    return Vector3.zero
end

---@param self SkillClientNative
---@param pos wrpc.PBVector3
---@return void
function SkillClientNative:ConvertServerPos(pos)
    return Vector3(pos.X, 0, pos.Y)
end

return SkillClientNative
