local PvPTileAssetHUDConstructionFlexibleMapBuilding = require("PvPTileAssetHUDConstructionFlexibleMapBuilding")

---@class PvPTileAssetHUDConstructionCommonMapBuilding:PvPTileAssetHUDConstructionFlexibleMapBuilding
---@field super PvPTileAssetHUDConstructionFlexibleMapBuilding
local PvPTileAssetHUDConstructionCommonMapBuilding = class("PvPTileAssetHUDConstructionCommonMapBuilding", PvPTileAssetHUDConstructionFlexibleMapBuilding)

return PvPTileAssetHUDConstructionCommonMapBuilding