---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2023/9/26 15:11
---
local CityCitizenPrefabLoaderSchema = {
    {"p_prefabName", typeof(CS.System.String)},
    {"p_stateName", typeof(CS.System.String)}
}

return CityCitizenPrefabLoaderSchema