---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shoufeng.zhang.
--- DateTime: 2022/4/22 15:15
---
local BaseToggleButton = require('BaseToggleButton')
local Delegate = require('Delegate')


---@class ToggleButtonStatusData
---@field buttonTextCompName string
---@field buttonText string

---@class ToggleButtonData:BaseToggleButtonData
---@field defaultStatus ToggleButtonStatusEnum
---@field statusDatas ToggleButtonStatusData[]

---@class StatusToggleData
---@field onButtonClick fun(button:StatusRecordToggleButton):void
---@field data ToggleButtonData

---@class StatusRecordToggleButton : BaseToggleButton
local StatusRecordToggleButton = class('StatusRecordToggleButton',BaseToggleButton)

---@type ToggleButtonStatusEnum
StatusRecordToggleButton.ButtonStatusEnum = {
    Selected = 0,
    Normal = 1,
    Locked = 2,
}

function StatusRecordToggleButton:OnCreate(param)
    self.button = self:Button('',Delegate.GetOrCreate(self,self.OnButtonClick))
    self.statusRecord = self:BindComponent('', typeof(CS.StatusRecordParent))    
end

---@param data StatusToggleData
function StatusRecordToggleButton:OnFeedData(data)
    self.groupCallback = data.onButtonClick
    local btnData = data.data
    self.isLocked = btnData.defaultStatus == StatusRecordToggleButton.ButtonStatusEnum.Locked
    if btnData.statusDatas and #btnData.statusDatas > 0 then
        for i = 1, #btnData.statusDatas do
            local statusData = btnData.statusDatas[i]
            if statusData ~= nil then
                self:Text(statusData.buttonTextCompName,statusData.buttonText)                                                
            end             
        end        
    end   
    self.statusRecord:Play(btnData.defaultStatus)    
end

function StatusRecordToggleButton:OnButtonClick()
    if not self.isLocked and self.groupCallback ~= nil then
        self.groupCallback(self)
    end
end

function StatusRecordToggleButton:OnSelected()
    if not self.isLocked and self.statusRecord then
        self.statusRecord:Play(StatusRecordToggleButton.ButtonStatusEnum.Selected)
    end
end

function StatusRecordToggleButton:OnDeselected()
    if not self.isLocked and self.statusRecord then
        self.statusRecord:Play(StatusRecordToggleButton.ButtonStatusEnum.Normal)
    end
end

return StatusRecordToggleButton