---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by BE.Tenner.
--- DateTime: 2021/12/14 15:11
---

local SEFactionType =
{
    Self = -1,
    Neutral = 0,
    Hostile = 1,
    Friendly = 2,
}

return SEFactionType
