---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by BE.Tenner.
--- DateTime: 2022/5/20 13:20
---

--- 单位移动模式
local SEUnitLocomotionMode =
{
    -- 基于NavMesh
    NavMesh = 1,

    -- 直接
    Direct = 2,
}

return SEUnitLocomotionMode
