-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class AcceptNpcCitizenChapterParameter:BaseParameter
---@field new fun():AcceptNpcCitizenChapterParameter
local cls = class('AcceptNpcCitizenChapterParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.AcceptNpcCitizenChapter.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'AcceptNpcCitizenChapter'
end

function cls.GetMsgId()
    return 20921
end

return cls
