-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class ActivateAllianceActivityBattleParameter:BaseParameter
---@field new fun():ActivateAllianceActivityBattleParameter
local cls = class('ActivateAllianceActivityBattleParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.ActivateAllianceActivityBattle.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'ActivateAllianceActivityBattle'
end

function cls.GetMsgId()
    return 34258
end

return cls
