-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class AllianceConveneMembersParameter:BaseParameter
---@field new fun():AllianceConveneMembersParameter
local cls = class('AllianceConveneMembersParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.AllianceConveneMembers.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'AllianceConveneMembers'
end

function cls.GetMsgId()
    return 34293
end

return cls
