-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class ApplyForAllianceParameter:BaseParameter
---@field new fun():ApplyForAllianceParameter
local cls = class('ApplyForAllianceParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.ApplyForAlliance.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'ApplyForAlliance'
end

function cls.GetMsgId()
    return 34126
end

return cls
