-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class AskPlayerStatisticsParameter:BaseParameter
---@field new fun():AskPlayerStatisticsParameter
local cls = class('AskPlayerStatisticsParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.AskPlayerStatistics.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'AskPlayerStatistics'
end

function cls.GetMsgId()
    return 10202
end

return cls
