-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class BackToCityParameter:BaseParameter
---@field new fun():BackToCityParameter
local cls = class('BackToCityParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.BackToCity.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'BackToCity'
end

function cls.GetMsgId()
    return 21507
end

return cls
