-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class BuildEnergyTowerParameter:BaseParameter
---@field new fun():BuildEnergyTowerParameter
local cls = class('BuildEnergyTowerParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.BuildEnergyTower.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'BuildEnergyTower'
end

function cls.GetMsgId()
    return 25502
end

return cls
