-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CancelSignUpAllianceActivityBattleParameter:BaseParameter
---@field new fun():CancelSignUpAllianceActivityBattleParameter
local cls = class('CancelSignUpAllianceActivityBattleParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CancelSignUpAllianceActivityBattle.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CancelSignUpAllianceActivityBattle'
end

function cls.GetMsgId()
    return 34260
end

return cls
