-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CancelAllianceAssembleTroopParameter:BaseParameter
---@field new fun():CancelAllianceAssembleTroopParameter
local cls = class('CancelAllianceAssembleTroopParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CancelAllianceAssembleTroop.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CancelAllianceAssembleTroop'
end

function cls.GetMsgId()
    return 21530
end

return cls
