-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CancelAutoCatchPetParameter:BaseParameter
---@field new fun():CancelAutoCatchPetParameter
local cls = class('CancelAutoCatchPetParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CancelAutoCatchPet.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CancelAutoCatchPet'
end

function cls.GetMsgId()
    return 23025
end

return cls
