-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastleMilitiaEquipParameter:BaseParameter
---@field new fun():CastleMilitiaEquipParameter
local cls = class('CastleMilitiaEquipParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastleMilitiaEquip.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastleMilitiaEquip'
end

function cls.GetMsgId()
    return 23079
end

return cls
