-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastleWorkSpeedUpByItemsParameter:BaseParameter
---@field new fun():CastleWorkSpeedUpByItemsParameter
local cls = class('CastleWorkSpeedUpByItemsParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastleWorkSpeedUpByItems.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastleWorkSpeedUpByItems'
end

function cls.GetMsgId()
    return 23023
end

return cls
