-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastleStartWorkParameter:BaseParameter
---@field new fun():CastleStartWorkParameter
local cls = class('CastleStartWorkParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastleStartWork.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastleStartWork'
end

function cls.GetMsgId()
    return 23050
end

return cls
