-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastleCitizenReceiveParameter:BaseParameter
---@field new fun():CastleCitizenReceiveParameter
local cls = class('CastleCitizenReceiveParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastleCitizenReceive.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastleCitizenReceive'
end

function cls.GetMsgId()
    return 23081
end

return cls
