-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastleUnlockTechStageParameter:BaseParameter
---@field new fun():CastleUnlockTechStageParameter
local cls = class('CastleUnlockTechStageParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastleUnlockTechStage.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastleUnlockTechStage'
end

function cls.GetMsgId()
    return 23077
end

return cls
