-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastlePetCollectQueueParameter:BaseParameter
---@field new fun():CastlePetCollectQueueParameter
local cls = class('CastlePetCollectQueueParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastlePetCollectQueue.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastlePetCollectQueue'
end

function cls.GetMsgId()
    return 23035
end

return cls
