-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastleUnlockTechnologyParameter:BaseParameter
---@field new fun():CastleUnlockTechnologyParameter
local cls = class('CastleUnlockTechnologyParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastleUnlockTechnology.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastleUnlockTechnology'
end

function cls.GetMsgId()
    return 23075
end

return cls
