-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastleGetStockRoomResParameter:BaseParameter
---@field new fun():CastleGetStockRoomResParameter
local cls = class('CastleGetStockRoomResParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastleGetStockRoomRes.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastleGetStockRoomRes'
end

function cls.GetMsgId()
    return 23037
end

return cls
