-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastleAddPetParameter:BaseParameter
---@field new fun():CastleAddPetParameter
local cls = class('CastleAddPetParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastleAddPet.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastleAddPet'
end

function cls.GetMsgId()
    return 23028
end

return cls
