-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastleBuildingAddFromStorageParameter:BaseParameter
---@field new fun():CastleBuildingAddFromStorageParameter
local cls = class('CastleBuildingAddFromStorageParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastleBuildingAddFromStorage.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastleBuildingAddFromStorage'
end

function cls.GetMsgId()
    return 23073
end

return cls
