-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastleBuildingUpgradeParameter:BaseParameter
---@field new fun():CastleBuildingUpgradeParameter
local cls = class('CastleBuildingUpgradeParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastleBuildingUpgrade.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastleBuildingUpgrade'
end

function cls.GetMsgId()
    return 23044
end

return cls
