-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastleStopAutoProcessParameter:BaseParameter
---@field new fun():CastleStopAutoProcessParameter
local cls = class('CastleStopAutoProcessParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastleStopAutoProcess.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastleStopAutoProcess'
end

function cls.GetMsgId()
    return 23084
end

return cls
