-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastleBuildingRepairWallParameter:BaseParameter
---@field new fun():CastleBuildingRepairWallParameter
local cls = class('CastleBuildingRepairWallParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastleBuildingRepairWall.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastleBuildingRepairWall'
end

function cls.GetMsgId()
    return 23093
end

return cls
