-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastleBuildingChangeWallsParameter:BaseParameter
---@field new fun():CastleBuildingChangeWallsParameter
local cls = class('CastleBuildingChangeWallsParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastleBuildingChangeWalls.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastleBuildingChangeWalls'
end

function cls.GetMsgId()
    return 23106
end

return cls
