-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastleDelFurnitureResGenProcessParameter:BaseParameter
---@field new fun():CastleDelFurnitureResGenProcessParameter
local cls = class('CastleDelFurnitureResGenProcessParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastleDelFurnitureResGenProcess.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastleDelFurnitureResGenProcess'
end

function cls.GetMsgId()
    return 23017
end

return cls
