-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastleBuildingAddDoorParameter:BaseParameter
---@field new fun():CastleBuildingAddDoorParameter
local cls = class('CastleBuildingAddDoorParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastleBuildingAddDoor.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastleBuildingAddDoor'
end

function cls.GetMsgId()
    return 23096
end

return cls
