-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastleSoldierCancelEquipParameter:BaseParameter
---@field new fun():CastleSoldierCancelEquipParameter
local cls = class('CastleSoldierCancelEquipParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastleSoldierCancelEquip.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastleSoldierCancelEquip'
end

function cls.GetMsgId()
    return 23080
end

return cls
