-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CastleGetFurnitureResParameter:BaseParameter
---@field new fun():CastleGetFurnitureResParameter
local cls = class('CastleGetFurnitureResParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CastleGetFurnitureRes.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CastleGetFurnitureRes'
end

function cls.GetMsgId()
    return 23030
end

return cls
