-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class ChangeDirectEnterParameter:BaseParameter
---@field new fun():ChangeDirectEnterParameter
local cls = class('ChangeDirectEnterParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.ChangeDirectEnter.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'ChangeDirectEnter'
end

function cls.GetMsgId()
    return 34308
end

return cls
