-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class ChangeServerTimeRateParameter:BaseParameter
---@field new fun():ChangeServerTimeRateParameter
local cls = class('ChangeServerTimeRateParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.ChangeServerTimeRate.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'ChangeServerTimeRate'
end

function cls.GetMsgId()
    return 20747
end

return cls
