-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class ChangeAllianceCenterParameter:BaseParameter
---@field new fun():ChangeAllianceCenterParameter
local cls = class('ChangeAllianceCenterParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.ChangeAllianceCenter.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'ChangeAllianceCenter'
end

function cls.GetMsgId()
    return 34289
end

return cls
