-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class ClaimMailAttachmentParameter:BaseParameter
---@field new fun():ClaimMailAttachmentParameter
local cls = class('ClaimMailAttachmentParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.ClaimMailAttachment.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'ClaimMailAttachment'
end

function cls.GetMsgId()
    return 23607
end

return cls
