-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class ClearHaveGetGiftsParameter:BaseParameter
---@field new fun():ClearHaveGetGiftsParameter
local cls = class('ClearHaveGetGiftsParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.ClearHaveGetGifts.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'ClearHaveGetGifts'
end

function cls.GetMsgId()
    return 34276
end

return cls
