-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CreateAllianceParameter:BaseParameter
---@field new fun():CreateAllianceParameter
local cls = class('CreateAllianceParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CreateAlliance.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CreateAlliance'
end

function cls.GetMsgId()
    return 34101
end

return cls
