-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CreateTeamTrusteeshipParameter:BaseParameter
---@field new fun():CreateTeamTrusteeshipParameter
local cls = class('CreateTeamTrusteeshipParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CreateTeamTrusteeship.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CreateTeamTrusteeship'
end

function cls.GetMsgId()
    return 21523
end

return cls
