-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class CreateTroopParameter:BaseParameter
---@field new fun():CreateTroopParameter
local cls = class('CreateTroopParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.CreateTroop.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'CreateTroop'
end

function cls.GetMsgId()
    return 21509
end

return cls
