-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class DailyRewardClimbTowerParameter:BaseParameter
---@field new fun():DailyRewardClimbTowerParameter
local cls = class('DailyRewardClimbTowerParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.DailyRewardClimbTower.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'DailyRewardClimbTower'
end

function cls.GetMsgId()
    return 20863
end

return cls
