-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class DailyTaskRefreshNormalTaskParameter:BaseParameter
---@field new fun():DailyTaskRefreshNormalTaskParameter
local cls = class('DailyTaskRefreshNormalTaskParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.DailyTaskRefreshNormalTask.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'DailyTaskRefreshNormalTask'
end

function cls.GetMsgId()
    return 20762
end

return cls
