-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class DebugCmdStringParameter:BaseParameter
---@field new fun():DebugCmdStringParameter
local cls = class('DebugCmdStringParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.DebugCmdString.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'DebugCmdString'
end

function cls.GetMsgId()
    return 10004
end

return cls
