-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class DeleteMailsParameter:BaseParameter
---@field new fun():DeleteMailsParameter
local cls = class('DeleteMailsParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.DeleteMails.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'DeleteMails'
end

function cls.GetMsgId()
    return 23605
end

return cls
