-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class DiscardItemParameter:BaseParameter
---@field new fun():DiscardItemParameter
local cls = class('DiscardItemParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.DiscardItem.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'DiscardItem'
end

function cls.GetMsgId()
    return 10200
end

return cls
