-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class DismissTroopPresetParameter:BaseParameter
---@field new fun():DismissTroopPresetParameter
local cls = class('DismissTroopPresetParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.DismissTroopPreset.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'DismissTroopPreset'
end

function cls.GetMsgId()
    return 21506
end

return cls
