-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class DropVillageParameter:BaseParameter
---@field new fun():DropVillageParameter
local cls = class('DropVillageParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.DropVillage.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'DropVillage'
end

function cls.GetMsgId()
    return 34268
end

return cls
