-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class EnterSceneToClearSlgCreepParameter:BaseParameter
---@field new fun():EnterSceneToClearSlgCreepParameter
local cls = class('EnterSceneToClearSlgCreepParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.EnterSceneToClearSlgCreep.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'EnterSceneToClearSlgCreep'
end

function cls.GetMsgId()
    return 25514
end

return cls
