-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class EnterSceneParameter:BaseParameter
---@field new fun():EnterSceneParameter
local cls = class('EnterSceneParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.EnterScene.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'EnterScene'
end

function cls.GetMsgId()
    return 23401
end

return cls
