-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class EquipItemParameter:BaseParameter
---@field new fun():EquipItemParameter
local cls = class('EquipItemParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.EquipItem.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'EquipItem'
end

function cls.GetMsgId()
    return 21516
end

return cls
