-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class ExchangeItemParameter:BaseParameter
---@field new fun():ExchangeItemParameter
local cls = class('ExchangeItemParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.ExchangeItem.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'ExchangeItem'
end

function cls.GetMsgId()
    return 10212
end

return cls
