-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class FavourMailsParameter:BaseParameter
---@field new fun():FavourMailsParameter
local cls = class('FavourMailsParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.FavourMails.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'FavourMails'
end

function cls.GetMsgId()
    return 23606
end

return cls
