-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class FinishExploreRadarTaskParameter:BaseParameter
---@field new fun():FinishExploreRadarTaskParameter
local cls = class('FinishExploreRadarTaskParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.FinishExploreRadarTask.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'FinishExploreRadarTask'
end

function cls.GetMsgId()
    return 25006
end

return cls
