-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class ForgeEquipmentParameter:BaseParameter
---@field new fun():ForgeEquipmentParameter
local cls = class('ForgeEquipmentParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.ForgeEquipment.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'ForgeEquipment'
end

function cls.GetMsgId()
    return 20720
end

return cls
