-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class GetAllianceGiftRewardParameter:BaseParameter
---@field new fun():GetAllianceGiftRewardParameter
local cls = class('GetAllianceGiftRewardParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.GetAllianceGiftReward.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'GetAllianceGiftReward'
end

function cls.GetMsgId()
    return 34254
end

return cls
