-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class GetNormalAllianceGiftRewardParameter:BaseParameter
---@field new fun():GetNormalAllianceGiftRewardParameter
local cls = class('GetNormalAllianceGiftRewardParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.GetNormalAllianceGiftReward.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'GetNormalAllianceGiftReward'
end

function cls.GetMsgId()
    return 34255
end

return cls
