-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class GetPetHandbookRewardParameter:BaseParameter
---@field new fun():GetPetHandbookRewardParameter
local cls = class('GetPetHandbookRewardParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.GetPetHandbookReward.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'GetPetHandbookReward'
end

function cls.GetMsgId()
    return 24206
end

return cls
