-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class HeroBreakThroughParameter:BaseParameter
---@field new fun():HeroBreakThroughParameter
local cls = class('HeroBreakThroughParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.HeroBreakThrough.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'HeroBreakThrough'
end

function cls.GetMsgId()
    return 24012
end

return cls
