-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class HeroPieceToHeroParameter:BaseParameter
---@field new fun():HeroPieceToHeroParameter
local cls = class('HeroPieceToHeroParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.HeroPieceToHero.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'HeroPieceToHero'
end

function cls.GetMsgId()
    return 24025
end

return cls
