-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class JoinTeamTrusteeshipParameter:BaseParameter
---@field new fun():JoinTeamTrusteeshipParameter
local cls = class('JoinTeamTrusteeshipParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.JoinTeamTrusteeship.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'JoinTeamTrusteeship'
end

function cls.GetMsgId()
    return 21525
end

return cls
