-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class KickAllianceActivityBattleMemberParameter:BaseParameter
---@field new fun():KickAllianceActivityBattleMemberParameter
local cls = class('KickAllianceActivityBattleMemberParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.KickAllianceActivityBattleMember.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'KickAllianceActivityBattleMember'
end

function cls.GetMsgId()
    return 34263
end

return cls
