-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class KickMemberParameter:BaseParameter
---@field new fun():KickMemberParameter
local cls = class('KickMemberParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.KickMember.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'KickMember'
end

function cls.GetMsgId()
    return 34304
end

return cls
