-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class LearnTalentSkillParameter:BaseParameter
---@field new fun():LearnTalentSkillParameter
local cls = class('LearnTalentSkillParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.LearnTalentSkill.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'LearnTalentSkill'
end

function cls.GetMsgId()
    return 20718
end

return cls
