-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class LeaveSceneNewParameter:BaseParameter
---@field new fun():LeaveSceneNewParameter
local cls = class('LeaveSceneNewParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.LeaveSceneNew.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'LeaveSceneNew'
end

function cls.GetMsgId()
    return 23410
end

return cls
