-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class MoveStepParameter:BaseParameter
---@field new fun():MoveStepParameter
local cls = class('MoveStepParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.MoveStep.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'MoveStep'
end

function cls.GetMsgId()
    return 20733
end

return cls
