-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class MoveMobileFortressParameter:BaseParameter
---@field new fun():MoveMobileFortressParameter
local cls = class('MoveMobileFortressParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.MoveMobileFortress.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'MoveMobileFortress'
end

function cls.GetMsgId()
    return 25506
end

return cls
