-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class OneKeyArrangePresetParameter:BaseParameter
---@field new fun():OneKeyArrangePresetParameter
local cls = class('OneKeyArrangePresetParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.OneKeyArrangePreset.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'OneKeyArrangePreset'
end

function cls.GetMsgId()
    return 21534
end

return cls
