-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class OpenAllianceEnergyBoxParameter:BaseParameter
---@field new fun():OpenAllianceEnergyBoxParameter
local cls = class('OpenAllianceEnergyBoxParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.OpenAllianceEnergyBox.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'OpenAllianceEnergyBox'
end

function cls.GetMsgId()
    return 34256
end

return cls
