-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class PetHandbookSignNameParameter:BaseParameter
---@field new fun():PetHandbookSignNameParameter
local cls = class('PetHandbookSignNameParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.PetHandbookSignName.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'PetHandbookSignName'
end

function cls.GetMsgId()
    return 24209
end

return cls
