-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class PetLearnSkillParameter:BaseParameter
---@field new fun():PetLearnSkillParameter
local cls = class('PetLearnSkillParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.PetLearnSkill.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'PetLearnSkill'
end

function cls.GetMsgId()
    return 24224
end

return cls
