-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class PetUnlockStoryParameter:BaseParameter
---@field new fun():PetUnlockStoryParameter
local cls = class('PetUnlockStoryParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.PetUnlockStory.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'PetUnlockStory'
end

function cls.GetMsgId()
    return 24211
end

return cls
