-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class PetWildCatchUseItemParameter:BaseParameter
---@field new fun():PetWildCatchUseItemParameter
local cls = class('PetWildCatchUseItemParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.PetWildCatchUseItem.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'PetWildCatchUseItem'
end

function cls.GetMsgId()
    return 24204
end

return cls
