-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class PlayerAutoRewardOpParameter:BaseParameter
---@field new fun():PlayerAutoRewardOpParameter
local cls = class('PlayerAutoRewardOpParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.PlayerAutoRewardOp.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'PlayerAutoRewardOp'
end

function cls.GetMsgId()
    return 20886
end

return cls
