-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class PlayerOneClickGetRewardBoxParameter:BaseParameter
---@field new fun():PlayerOneClickGetRewardBoxParameter
local cls = class('PlayerOneClickGetRewardBoxParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.PlayerOneClickGetRewardBox.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'PlayerOneClickGetRewardBox'
end

function cls.GetMsgId()
    return 20888
end

return cls
