-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class RadarLevelUpParameter:BaseParameter
---@field new fun():RadarLevelUpParameter
local cls = class('RadarLevelUpParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.RadarLevelUp.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'RadarLevelUp'
end

function cls.GetMsgId()
    return 20781
end

return cls
