-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class RadarLevelRewardTasksParameter:BaseParameter
---@field new fun():RadarLevelRewardTasksParameter
local cls = class('RadarLevelRewardTasksParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.RadarLevelRewardTasks.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'RadarLevelRewardTasks'
end

function cls.GetMsgId()
    return 25007
end

return cls
