-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class ReadAllianceLeaderChangeParameter:BaseParameter
---@field new fun():ReadAllianceLeaderChangeParameter
local cls = class('ReadAllianceLeaderChangeParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.ReadAllianceLeaderChange.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'ReadAllianceLeaderChange'
end

function cls.GetMsgId()
    return 34281
end

return cls
