-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class ReadMailsAndClaimAllParameter:BaseParameter
---@field new fun():ReadMailsAndClaimAllParameter
local cls = class('ReadMailsAndClaimAllParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.ReadMailsAndClaimAll.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'ReadMailsAndClaimAll'
end

function cls.GetMsgId()
    return 23608
end

return cls
