-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class ReceivePlanProgressRewardParameter:BaseParameter
---@field new fun():ReceivePlanProgressRewardParameter
local cls = class('ReceivePlanProgressRewardParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.ReceivePlanProgressReward.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'ReceivePlanProgressReward'
end

function cls.GetMsgId()
    return 20928
end

return cls
