-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class ReceiveActivityRewardParameter:BaseParameter
---@field new fun():ReceiveActivityRewardParameter
local cls = class('ReceiveActivityRewardParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.ReceiveActivityReward.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'ReceiveActivityReward'
end

function cls.GetMsgId()
    return 20831
end

return cls
