-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class RequestNpcServiceParameter:BaseParameter
---@field new fun():RequestNpcServiceParameter
local cls = class('RequestNpcServiceParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.RequestNpcService.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'RequestNpcService'
end

function cls.GetMsgId()
    return 25302
end

return cls
