-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class RoundRobinPetCardParameter:BaseParameter
---@field new fun():RoundRobinPetCardParameter
local cls = class('RoundRobinPetCardParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.RoundRobinPetCard.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'RoundRobinPetCard'
end

function cls.GetMsgId()
    return 21533
end

return cls
