-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class SceneLoadFinishParameter:BaseParameter
---@field new fun():SceneLoadFinishParameter
local cls = class('SceneLoadFinishParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.SceneLoadFinish.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'SceneLoadFinish'
end

function cls.GetMsgId()
    return 23406
end

return cls
