-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class SendAllianceHelpsParameter:BaseParameter
---@field new fun():SendAllianceHelpsParameter
local cls = class('SendAllianceHelpsParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.SendAllianceHelps.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'SendAllianceHelps'
end

function cls.GetMsgId()
    return 34146
end

return cls
