-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class SendMailParameter:BaseParameter
---@field new fun():SendMailParameter
local cls = class('SendMailParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.SendMail.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'SendMail'
end

function cls.GetMsgId()
    return 23602
end

return cls
