-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class SendClientDataReadyReParameter:BaseParameter
---@field new fun():SendClientDataReadyReParameter
local cls = class('SendClientDataReadyReParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.SendClientDataReadyRe.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'SendClientDataReadyRe'
end

function cls.GetMsgId()
    return 10215
end

return cls
