-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class SetAllianceRankParameter:BaseParameter
---@field new fun():SetAllianceRankParameter
local cls = class('SetAllianceRankParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.SetAllianceRank.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'SetAllianceRank'
end

function cls.GetMsgId()
    return 34136
end

return cls
