-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class SetAutoBackAfterClearExpeditionParameter:BaseParameter
---@field new fun():SetAutoBackAfterClearExpeditionParameter
local cls = class('SetAutoBackAfterClearExpeditionParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.SetAutoBackAfterClearExpedition.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'SetAutoBackAfterClearExpedition'
end

function cls.GetMsgId()
    return 21535
end

return cls
