-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class SetAllianceTitleParameter:BaseParameter
---@field new fun():SetAllianceTitleParameter
local cls = class('SetAllianceTitleParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.SetAllianceTitle.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'SetAllianceTitle'
end

function cls.GetMsgId()
    return 34137
end

return cls
