-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class SetAutoFulfillHpParameter:BaseParameter
---@field new fun():SetAutoFulfillHpParameter
local cls = class('SetAutoFulfillHpParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.SetAutoFulfillHp.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'SetAutoFulfillHp'
end

function cls.GetMsgId()
    return 21522
end

return cls
