-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class SetTroopAutoBack2CityParameter:BaseParameter
---@field new fun():SetTroopAutoBack2CityParameter
local cls = class('SetTroopAutoBack2CityParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.SetTroopAutoBack2City.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'SetTroopAutoBack2City'
end

function cls.GetMsgId()
    return 21511
end

return cls
