-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class SignUpAllianceActivityBattleParameter:BaseParameter
---@field new fun():SignUpAllianceActivityBattleParameter
local cls = class('SignUpAllianceActivityBattleParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.SignUpAllianceActivityBattle.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'SignUpAllianceActivityBattle'
end

function cls.GetMsgId()
    return 34259
end

return cls
