-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class StarRewardHuntingParameter:BaseParameter
---@field new fun():StarRewardHuntingParameter
local cls = class('StarRewardHuntingParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.StarRewardHunting.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'StarRewardHunting'
end

function cls.GetMsgId()
    return 20871
end

return cls
