-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class StartImpeachAllianceLeaderParameter:BaseParameter
---@field new fun():StartImpeachAllianceLeaderParameter
local cls = class('StartImpeachAllianceLeaderParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.StartImpeachAllianceLeader.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'StartImpeachAllianceLeader'
end

function cls.GetMsgId()
    return 34279
end

return cls
