-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class StartRuinRebuildParameter:BaseParameter
---@field new fun():StartRuinRebuildParameter
local cls = class('StartRuinRebuildParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.StartRuinRebuild.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'StartRuinRebuild'
end

function cls.GetMsgId()
    return 34296
end

return cls
