-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class StoryStartParameter:BaseParameter
---@field new fun():StoryStartParameter
local cls = class('StoryStartParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.StoryStart.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'StoryStart'
end

function cls.GetMsgId()
    return 20729
end

return cls
