-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class SyncPushDeviceTokenParameter:BaseParameter
---@field new fun():SyncPushDeviceTokenParameter
local cls = class('SyncPushDeviceTokenParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.SyncPushDeviceToken.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'SyncPushDeviceToken'
end

function cls.GetMsgId()
    return 25602
end

return cls
