-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class SyncDeviceInfoParameter:BaseParameter
---@field new fun():SyncDeviceInfoParameter
local cls = class('SyncDeviceInfoParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.SyncDeviceInfo.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'SyncDeviceInfo'
end

function cls.GetMsgId()
    return 25601
end

return cls
