-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class TauntMobParameter:BaseParameter
---@field new fun():TauntMobParameter
local cls = class('TauntMobParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.TauntMob.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'TauntMob'
end

function cls.GetMsgId()
    return 10208
end

return cls
