-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class TeamTrusteeshipKickOutParameter:BaseParameter
---@field new fun():TeamTrusteeshipKickOutParameter
local cls = class('TeamTrusteeshipKickOutParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.TeamTrusteeshipKickOut.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'TeamTrusteeshipKickOut'
end

function cls.GetMsgId()
    return 21527
end

return cls
