-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class TraceStepParameter:BaseParameter
---@field new fun():TraceStepParameter
local cls = class('TraceStepParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.TraceStep.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'TraceStep'
end

function cls.GetMsgId()
    return 20713
end

return cls
