-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class TroopSetAutoBattleParameter:BaseParameter
---@field new fun():TroopSetAutoBattleParameter
local cls = class('TroopSetAutoBattleParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.TroopSetAutoBattle.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'TroopSetAutoBattle'
end

function cls.GetMsgId()
    return 21536
end

return cls
