-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class TroopPresetChooseHeroParameter:BaseParameter
---@field new fun():TroopPresetChooseHeroParameter
local cls = class('TroopPresetChooseHeroParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.TroopPresetChooseHero.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'TroopPresetChooseHero'
end

function cls.GetMsgId()
    return 20751
end

return cls
