-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class TroopGoToBattleParameter:BaseParameter
---@field new fun():TroopGoToBattleParameter
local cls = class('TroopGoToBattleParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.TroopGoToBattle.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'TroopGoToBattle'
end

function cls.GetMsgId()
    return 21518
end

return cls
