-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class TryCancelInteractParameter:BaseParameter
---@field new fun():TryCancelInteractParameter
local cls = class('TryCancelInteractParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.TryCancelInteract.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'TryCancelInteract'
end

function cls.GetMsgId()
    return 23501
end

return cls
