-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class TryInteractSlgParameter:BaseParameter
---@field new fun():TryInteractSlgParameter
local cls = class('TryInteractSlgParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.TryInteractSlg.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'TryInteractSlg'
end

function cls.GetMsgId()
    return 23502
end

return cls
