-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class TryInteractSeParameter:BaseParameter
---@field new fun():TryInteractSeParameter
local cls = class('TryInteractSeParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.TryInteractSe.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'TryInteractSe'
end

function cls.GetMsgId()
    return 23557
end

return cls
