-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class UnlockMistParameter:BaseParameter
---@field new fun():UnlockMistParameter
local cls = class('UnlockMistParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.UnlockMist.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'UnlockMist'
end

function cls.GetMsgId()
    return 20771
end

return cls
