-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class UpdateRecruitTimeParameter:BaseParameter
---@field new fun():UpdateRecruitTimeParameter
local cls = class('UpdateRecruitTimeParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.UpdateRecruitTime.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'UpdateRecruitTime'
end

function cls.GetMsgId()
    return 34290
end

return cls
