-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class UploadCustomAvatarParameter:BaseParameter
---@field new fun():UploadCustomAvatarParameter
local cls = class('UploadCustomAvatarParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.UploadCustomAvatar.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'UploadCustomAvatar'
end

function cls.GetMsgId()
    return 24304
end

return cls
