-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class UsePetEggParameter:BaseParameter
---@field new fun():UsePetEggParameter
local cls = class('UsePetEggParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.UsePetEgg.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'UsePetEgg'
end

function cls.GetMsgId()
    return 24235
end

return cls
