-- THIS FILE GENERATED BY TOOL, DO NOT MODIFY IT!

local BaseParameter = require('BaseParameter')

---@class VoteStageAndRewardParameter:BaseParameter
---@field new fun():VoteStageAndRewardParameter
local cls = class('VoteStageAndRewardParameter', BaseParameter)

---@private
function cls:ctor()
    self.msg = rpc.VoteStageAndReward.New()
    self.args = self.msg.request
end

function cls.GetMsgName()
    return 'VoteStageAndReward'
end

function cls.GetMsgId()
    return 20709
end

return cls
