---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shoufeng.zhang.
--- DateTime: 2022/4/22 15:15
---
local BaseToggleButton = require('BaseToggleButton')
local Delegate = require('Delegate')
local I18N = require("I18N")

---@class UIHeroMainPageCtrlToggleButton : BaseToggleButton
local UIHeroMainPageCtrlToggleButton = class('UIHeroMainPageCtrlToggleButton',BaseToggleButton)

function UIHeroMainPageCtrlToggleButton:OnCreate(param)
    self.button = self:Button('',Delegate.GetOrCreate(self,self.OnButtonClick))
    self.statusRecord = self:BindComponent('', typeof(CS.StatusRecordParent))
    self.textB = self:Text('p_text_b')
    self.textA = self:Text('p_text_a')
    self.textC = self:Text('p_text_c')
    self.notifyNode = self:LuaObject('child_reddot_default')
end

function UIHeroMainPageCtrlToggleButton:OnFeedData(data)
    self.groupCallback = data.onButtonClick
    self.data = data.data
    if self.data ~= nil then
        self.textA.text = I18N.Get(self.data.name)
        self.textB.text = I18N.Get(self.data.name)
        self.textC.text = I18N.Get(self.data.name)
        self.isLocked = self.data.isLocked
    end

    if self.isLocked then
        self.statusRecord:Play(2)
    end
end

function UIHeroMainPageCtrlToggleButton:OnButtonClick()
    if self.groupCallback ~= nil and not self.isLocked then
        self.groupCallback(self)
    end
end

function UIHeroMainPageCtrlToggleButton:OnSelected()
    if self.statusRecord and not self.isLocked then
        self.statusRecord:Play(0)
    end
end

function UIHeroMainPageCtrlToggleButton:OnDeselected()
    if self.statusRecord and not self.isLocked then
        self.statusRecord:Play(1)
    end
end

return UIHeroMainPageCtrlToggleButton