---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shoufeng.zhang.
--- DateTime: 2022/1/12 20:37
---
local BaseUIMediator = require("BaseUIMediator")
local Delegate = require("Delegate")
local ModuleRefer = require('ModuleRefer')
local I18N = require('I18N')
local TimerUtility = require('TimerUtility')
local AudioConst = require("AudioConsts")

---@class NewChapterUIMediator : BaseUIMediator
---@field _module QuestModule_Chapter
local NewChapterUIMediator = class('NewChapterUIMediator',BaseUIMediator)

function NewChapterUIMediator:ctor()
    self._module = ModuleRefer.QuestModule.Chapter;
end

function NewChapterUIMediator:OnCreate(param)
    self._module:OnChapterGroupUnlockAnimPlayed()
    self._textUnlock = self:Text('p_text_unlock', I18N.Get("task_newchapter_unlock"))
    self._txtTitle = self:Text('p_text_chapter');
    self._txtTarget = self:Text('p_text_target');
    self._txtHint = self:Text('p_text_hint');
    self._imageBG1 = self:Image('p_base_chapter_1');
    self._imageBG2 = self:Image('p_base_chapter_2');
    self._imageBG3 = self:Image('p_base_chapter_3');
    self._imageBG4 = self:Image('p_base_chapter_4');
end

function NewChapterUIMediator:OnShow(param)
    local cfgCell = self._module:CurrentChapterGroup()
    self._txtTitle.text = I18N.Get(cfgCell:Title())
    self._txtTarget.text = I18N.Get(cfgCell:Desc())
    self._txtHint.text = I18N.Get(cfgCell:Hint())
    self:LoadSprite(cfgCell:TargetPic(),self._imageBG1)
    self:LoadSprite(cfgCell:TargetPic(),self._imageBG2)
    self:LoadSprite(cfgCell:TargetPic(),self._imageBG3)
    self:LoadSprite(cfgCell:TargetPic(),self._imageBG4)
    --play anim
    --wait for anim end

    TimerUtility.DelayExecute( function()
        self:CloseSelf()
        if param ~= nil and param.onWinClose ~= nil then
            param.onWinClose()
        end
    end,2)
    g_Game.SoundManager:PlayAudio(AudioConst.sfx_ui_finish_task)

end

function NewChapterUIMediator:OnClose(param)

end


return NewChapterUIMediator