---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wupei.
--- DateTime: 2021/3/9
---

---@class TroopEffectUtil
local TroopEffectUtil = {}

---@param effect SlgPoolObject
function TroopEffectUtil.TrailClear(effect)
    local go = effect.transform.gameObject
    if go then
        go:SetActive(false)
        local trails = go:GetComponentsInChildren(typeof(CS.UnityEngine.TrailRenderer))
        for i = 0, trails.Length - 1 do
            local trail = trails[i]
            trail:Clear()
        end
        go:SetActive(true)
    end
end

return TroopEffectUtil