---@class EventConst
local EventConst = {
    TEST_EVENT = "TEST_EVENT",

    ON_LOW_MEMORY = "ON_LOW_MEMORY",

    --Localization
    LOCALIZATION_LANG_RELOADED = "LOCALIZATION_LANG_RELOADED",

    -- COMMON
    UI_BUTTON_CLICK_PRE = "UI_BUTTON_CLICK_PRE",

    --- Application Focus
    APPLICATION_FOCUS = "APPLICATION_FOCUS",

    --- Debug Only
    GAME_ERROR_CLEAR_TICK_DELEGATES = "GAME_ERROR_CLEAR_TICK_DELEGATES",

    --- Re-login Successfully
    RELOGIN_START = "RELOGIN_START",
    RELOGIN_SUCCESS = "RELOGIN_SUCCESS",
    RELOGIN_FAILURE = "RELOGIN_FAILURE",

    --- Loading Progress
    LOADING_PROGRESS_UPDATE = "LOADING_PROGRESS_UPDATE",
    REQUEST_LOADING_PROGRESS = "REQUEST_LOADING_PROGRESS",

    --- Login Step SelectServer
    LOGIN_SELECT_SERVER_REQUEST = "LOGIN_SELECT_SERVER_REQUEST",

    --- __Art\_Resources\KingdomMap\Prefab\Settings basic_camera_settings.Refresh()
    BASIC_CAMERA_SETTING_REFRESH = "BASIC_CAMERA_SETTING_REFRESH",

    --- WatcherConnection Destructed
    WATCHER_CONNECTION_DESTRUCTED = "WATCHER_CONNECTION_DESTRUCTED",

    --City
    CITY_RES_LOADED = "CITY_RES_LOADED",
    CITY_DATA_LOADED = "CITY_DATA_LOADED",
    CITY_VIEW_LOADED = "CITY_VIEW_LOADED",

    CITY_BASIC_RESOURCE_LOAD_FAILED = "CITY_BASIC_RESOURCE_LOAD_FAILED",
    CITY_DATA_LOAD_FAILED = "CITY_DATA_LOAD_FAILED",
    CITY_VIEW_LOAD_FAILED = "CITY_VIEW_LOAD_FAILED",

    CITY_GRID_ON_CELL_ADD = "CITY_GRID_ON_CELL_ADD",
    CITY_GRID_ON_CELL_UPDATE = "CITY_GRID_ON_CELL_UPDATE",
    CITY_GRID_ON_CELL_UPDATE_WITH_SIZE_CHANGE = "CITY_GRID_ON_CELL_UPDATE_WITH_SIZE_CHANGE",
    CITY_GRID_ON_CELL_REMOVE = "CITY_GRID_ON_CELL_REMOVE",
    CITY_GRID_ON_CELL_ID_CHANGED = "CITY_GRID_ON_CELL_ID_CHANGED",
    CITY_GRID_ON_CELL_MOVING = "CITY_GRID_ON_CELL_MOVING",

    CITY_BUILDING_SELECTION = "CITY_BUILDING_SELECTION",
    CITY_BUILDING_UICELL_DRAG_RELEASE = "CITY_BUILDING_UICELL_DRAG_RELEASE",
    CITY_BUILDING_PREVIEW_POS = "CITY_BUILDING_PREVIEW_POS",

    CITY_MOVING_SELECTION = "CITY_MOVING_SELECTION",
    CITY_MOVING_PREVIEW_POS = "CITY_MOVING_PREVIEW_POS",
    CITY_MOVING_UITILE_DRAG_RELEASE = "CITY_MOVING_UITILE_DRAG_RELEASE",

    CITY_BUILDING_EXIT_EDIT_MODE = "CITY_BUILDING_EXIT_EDIT_MODE",
    CITY_BUILDING_OPERATION_MOVING_START = "CITY_BUILDING_OPERATION_MOVING_START",
    CITY_BUILDING_OPERATION_MOVING_STOP = "CITY_BUILDING_OPERATION_MOVING_STOP",
    CITY_CHANGE_MOVING_LEGO_STATE = "CITY_CHANGE_MOVING_LEGO_STATE",

    CITY_BUILDING_STATUS_TO_NORMAL = "CITY_BUILDING_STATUS_TO_NORMAL",
    CITY_BUILDING_POLLUTED_IN = "CITY_BUILDING_POLLUTED_IN",
    CITY_BUILDING_POLLUTED_OUT = "CITY_BUILDING_POLLUTED_OUT",
    CITY_BUILDING_DEBUG_POLLUTED_IN = "CITY_BUILDING_DEBUG_POLLUTED_IN",
    CITY_BUILDING_DEBUG_POLLUTED_OUT = "CITY_BUILDING_DEBUG_POLLUTED_OUT",

    CITY_CONSTRUCTION_UI_HIDE = "CITY_CONSTRUCTION_UI_HIDE",
    CITY_CONSTRUCTION_UI_SHOW = "CITY_CONSTRUCTION_UI_SHOW",
    CITY_CONSTRUCTION_CONTINUE_PLACE = "CITY_CONSTRUCTION_CONTINUE_PLACE",
    CITY_CONSTRUCTION_CELL_GUIDE_FINGER = "CITY_CONSTRUCTION_CELL_GUIDE_FINGER",
    CITY_CONSTRUCTION_UI_SHOW_ROOM_SUBPAGE = "CITY_CONSTRUCTION_UI_SHOW_ROOM_SUBPAGE",
    CITY_CONSTRUCTION_UI_EXIT_ROOM_SUBPAGE = "CITY_CONSTRUCTION_UI_EXIT_ROOM_SUBPAGE",
    CITY_CONSTRUCTION_UI_ROOM_MOVE_STEP = "CITY_CONSTRUCTION_UI_ROOM_MOVE_STEP",
    CITY_CONSTRUCTION_ROOM_CELL_IDX = "CITY_CONSTRUCTION_ROOM_CELL_IDX",
    CITY_CONSTRUCTION_UI_SHOW_TIPS = "CITY_CONSTRUCTION_UI_SHOW_TIPS",
    CITY_CONSTRUCTION_UI_HIDE_TIPS = "CITY_CONSTRUCTION_UI_HIDE_TIPS",
    CITY_CONSTRUCTION_UI_SHOW_HINT = "CITY_CONSTRUCTION_UI_SHOW_HINT",
    CITY_CONSTRUCTION_UI_HIDE_HINT = "CITY_CONSTRUCTION_UI_HIDE_HINT",

    CITY_WALKABLE_CHANGE_CHECK = "CITY_WALKABLE_CHANGE_CHECK",

    CITY_CLICK_RESOURCE = "CITY_CLICK_RESOURCE",
    CITY_SET_ACTIVE = "CITY_SET_ACTIVE",

    CITY_GRID_LAYER_UPDATE = "CITY_GRID_LAYER_UPDATE",

    CITY_STATEMACHINE_STATE_CHANGED = "CITY_STATEMACHINE_STATE_CHANGED",

    CITY_ORDER_EXPLORER_TO_UNLOCK = "CITY_ORDER_EXPLORER_TO_UNLOCK",
    CITY_ORDER_EXPLORER_TO_UNLOCK_INTERACT_START = "CITY_ORDER_EXPLORER_TO_UNLOCK_INTERACT_START",
    CITY_ORDER_EXPLORER_TO_UNLOCK_INTERACT_PROGRESS = "CITY_ORDER_EXPLORER_TO_UNLOCK_INTERACT_PROGRESS",
    CITY_ORDER_EXPLORER_TO_UNLOCK_INTERACT_INTERRUPTED = "CITY_ORDER_EXPLORER_TO_UNLOCK_INTERACT_INTERRUPTED",
    CITY_ORDER_EXPLORER_TO_UNLOCK_CALLBACK = "CITY_ORDER_EXPLORER_TO_UNLOCK_CALLBACK",
    CITY_ORDER_EXPLORER_CAMERA_GOTO_EXPLORER = "CITY_ORDER_EXPLORER_CAMERA_GOTO_EXPLORER",
    CITY_ORDER_EXPLORER_TEAM_INTERACT_TARGET = "CITY_ORDER_EXPLORER_TEAM_INTERACT_TARGET",
    CITY_ORDER_EXPLORER_TEAM_MOVING_UPDATE = "CITY_ORDER_EXPLORER_TEAM_MOVING_UPDATE",
    CITY_ORDER_EXPLORER_TEAM_CLICK = "CITY_ORDER_EXPLORER_TEAM_CLICK",
    CITY_ORDER_EXPLORER_TEAM_ZONE_CLICK = "CITY_ORDER_EXPLORER_TEAM_ZONE_CLICK",
    CITY_ORDER_EXPLORER_SELECT = "CITY_ORDER_EXPLORER_SELECT",
    CITY_ORDER_EXPLORER_TEAM_OPERATE_MENU = "CITY_ORDER_EXPLORER_TEAM_OPERATE_MENU",
    CITY_ORDER_EXPLORER_STATUES_UPDATE = "CITY_ORDER_EXPLORER_STATUES_UPDATE",
    CITY_UNLOCK_EVENT = "CITY_UNLOCK_EVENT",
    CITY_FOG_UNLOCK_CHANGED = "CITY_FOG_UNLOCK_CHANGED",
    CITY_TRY_UNLOCK_ZONE = "CITY_TRY_UNLOCK_ZONE",
    CITY_ORDER_EXPLORER_SLG_TROOP_CLICK = "CITY_ORDER_EXPLORER_SLG_TROOP_CLICK",
    CITY_ORDER_EXPLORER_SLG_TROOP_DRAG_BEGIN = "CITY_ORDER_EXPLORER_SLG_TROOP_DRAG_BEGIN",
    CITY_ORDER_EXPLORER_SLG_TROOP_DRAG_UPDATE = "CITY_ORDER_EXPLORER_SLG_TROOP_DRAG_UPDATE",
    CITY_ORDER_EXPLORER_SLG_TROOP_DRAG_END = "CITY_ORDER_EXPLORER_SLG_TROOP_DRAG_END",
    CITY_ORDER_EXPLORER_SLG_TROOP_DRAG_CANCEL = "CITY_ORDER_EXPLORER_SLG_TROOP_DRAG_CANCEL",
    CITY_ORDER_EXPLORER_TEAM_CREATE = "CITY_ORDER_EXPLORER_TEAM_CREATE",
    CITY_ORDER_EXPLORER_TEAM_DESTROY = "CITY_ORDER_EXPLORER_TEAM_DESTROY",

    CITY_ELEMENT_NPC_CLICK_TRIGGER = "CITY_ELEMENT_NPC_CLICK_TRIGGER",
    CITY_ELEMENT_NPC_CLICK_GET_TREASURE = "CITY_ELEMENT_NPC_CLICK_GET_TREASURE",
    CITY_ELEMENT_PRE_REMOVE = "CITY_ELEMENT_PRE_REMOVE",
    CITY_ELEMENT_POLLUTED_IN = "CITY_ELEMENT_POLLUTED_IN",
    CITY_ELEMENT_POLLUTED_OUT = "CITY_ELEMENT_POLLUTED_OUT",
    CITY_ELEMENT_EXPLORER_RESPONSE_TO_NPC_CLICK = "CITY_ELEMENT_EXPLORER_RESPONSE_TO_NPC_CLICK",
    CITY_ELEMENT_IN_TIMELINE_VISIBLE_CHANGED = "CITY_ELEMENT_IN_TIMELINE_VISIBLE_CHANGED",
    CITY_ELEMENT_LOCKED_NONE_SHOWN_SERVICE_NPC_SELECTED = "CITY_ELEMENT_LOCKED_NONE_SHOWN_SERVICE_NPC_SELECTED",
    CITY_ELEMENT_NPC_ID_CACHE_REFRESH = "CITY_ELEMENT_NPC_ID_CACHE_REFRESH",
    CITY_ELEMENT_NPC_TREASURE_REFRESH = "CITY_ELEMENT_NPC_TREASURE_REFRESH",
    CITY_ELEMENT_NPC_TRIGGER_CATCH_EFFECT = "CITY_ELEMENT_NPC_TRIGGER_CATCH_EFFECT",
    CITY_ELEMENT_SPAWNER_CLICK_TRIGGER = "CITY_ELEMENT_SPAWNER_CLICK_TRIGGER",
    CITY_ELEMENT_NPC_BUBBLE_TMP_HIDE = "CITY_ELEMENT_NPC_BUBBLE_TMP_HIDE",
    CITY_ELEMENT_NPC_PLAY_INTERACE_AUDIO = "CITY_ELEMENT_NPC_PLAY_INTERACE_AUDIO",
    CITY_ELEMENT_NPC_BUBBLE_RANGE_EVENT_UPDATE = "CITY_ELEMENT_NPC_BUBBLE_RANGE_EVENT_UPDATE",

    CITY_ELEMENT_INPROGRESS_RESOURCE_REMOVED = "CITY_ELEMENT_INPROGRESS_RESOURCE_REMOVED",
    CITY_ELEMENT_RESOURCE_UPDATE_COLLECTED_BUBBLE = "CITY_ELEMENT_RESOURCE_UPDATE_COLLECTED_BUBBLE",    ---- 资源点采集气泡更新
    CITY_ELEMENT_RESOURCE_BE_HIT = "CITY_ELEMENT_RESOURCE_BE_HIT", ---- @params : elementId: number

    CITY_ELEMENT_CREEP_CLICK = "CITY_ELEMENT_CREEP_CLICK", ---点击菌毯节点, 召集探险小队前往
    CITY_CREEP_NODE_SHOW_MENU = "CITY_CREEP_NODE_SHOW_MENU", ---探险小队离目标足够近时进入菌毯节点的选中情况

    CITY_ZONE_STATUS_BATCH_CHANGED = "CITY_ZONE_STATUS_BATCH_CHANGED",
    CITY_ZONE_STATUS_CHANGED = "CITY_ZONE_STATUS_CHANGED", ---- @params : City, zoneId, oldStatus, newStatus
    CITY_ZONE_SERVER_PUSH_RECOVERED = "CITY_ZONE_SERVER_PUSH_RECOVERED", ---- @params : City, zoneId, recovered elementId[]
    CITY_ZONE_RECOVERED_PRESET_EFFECT_DELAY = "CITY_ZONE_RECOVERED_PRESET_EFFECT_DELAY", ---- @params : City, zoneId, delay ,recovered elementId[]
    CITY_ZONE_BUBBLE_STATUS_CHANGE = "CITY_ZONE_BUBBLE_STATUS_CHANGE",

    CITY_FOG_REMOVED_BY_WALL = "CITY_FOG_REMOVED_BY_WALL",
    CITY_FOG_DATA_CHANGED = "CITY_FOG_DATA_CHANGED",

    CITY_CASTLE_BRIEF_DELETE = "CITY_CASTLE_BRIEF_DELETE",

    CITY_BUBBLE_STATE_CHANGE = "CITY_BUBBLE_STATE_CHANGE",  ---- 内城气泡状态改变

    CITY_FURNITURE_DATA_LOADED = "CITY_FURNITURE_DATA_LOADED",

    CITY_PLACE_FURNITURE = "CITY_PLACE_FURNITURE",
    CITY_FURNITURE_ADD_FOR_PET = "CITY_FURNITURE_ADD_FOR_PET",
    CITY_STORAGE_FURNITURE = "CITY_STORAGE_FURNITURE",
    CITY_FURNITURE_REMOVE_FOR_PET = "CITY_FURNITURE_REMOVE_FOR_PET",
    CITY_MOVING_FURNITURE = "CITY_MOVING_FURNITURE",
    CITY_BATCH_MOVING_FURNITURE = "CITY_BATCH_MOVING_FURNITURE", ---- params : City, table<number, CityFurniture>
    CITY_UPDATE_FURNITURE = "CITY_UPDATE_FURNITURE",
    CITY_FURNITURE_POLLUTED_IN = "CITY_FURNITURE_POLLUTED_IN",
    CITY_FURNITURE_POLLUTED_OUT = "CITY_FURNITURE_POLLUTED_OUT",

    CITY_FURNITURE_ADD = "CITY_FURNITURE_ADD", ---- params : City, CityFurniture
    CITY_FURNITURE_REMOVE = "CITY_FURNITURE_REMOVE", ---- params : City, CityFurniture

    CITY_FURNITURE_LEVEL_UP_FOR_GUIDE = "CITY_FURNITURE_LEVEL_UP_FOR_GUIDE",
    CITY_MAIN_BASE_FURNITURE_LEVEL_UP_FOR_GUIDE = "CITY_MAIN_BASE_FURNITURE_LEVEL_UP_FOR_GUIDE",

    CITY_STATIC_TILE_ADD = "CITY_STATIC_TILE_ADD",
    CITY_STATIC_TILE_REMOVE = "CITY_STATIC_TILE_REMOVE",

    CITY_GENERATING_RES_ADD = "CITY_GENERATING_RES_ADD",
    CITY_GENERATING_RES_REMOVE = "CITY_GENERATING_RES_REMOVE",

    CITY_SAFE_AREA_STATUS_REFRESH = "CITY_SAFE_AREA_STATUS_REFRESH",
    CITY_SAFE_AREA_WALL_STATUS_REFRESH = "CITY_SAFE_AREA_WALL_STATUS_REFRESH",
    CITY_SAFE_AREA_WALL_OR_DOOR_PLACE = "CITY_SAFE_AREA_WALL_OR_DOOR_PLACE",
    CITY_SAFE_AREA_WALL_OR_DOOR_REMOVE = "CITY_SAFE_AREA_WALL_OR_DOOR_REMOVE",
    CITY_SAFE_AREA_WALL_OR_DOOR_UPDATE = "CITY_SAFE_AREA_WALL_OR_DOOR_UPDATE",
    CITY_SAFE_AREA_WALL_OR_DOOR_SELECT_FILLED = "CITY_SAFE_AREA_WALL_OR_DOOR_SELECT_FILLED",
    CITY_SAFE_AREA_DOOR_OPEN_STATUS_CHANGED = "CITY_SAFE_AREA_DOOR_OPEN_STATUS_CHANGED",
    CITY_SAFE_AREA_MAP_CACHE_REBUILT = "CITY_SAFE_AREA_MAP_CACHE_REBUILT",

    CITY_FURNITURE_FARMLAND_UPDATE = "CITY_FURNITURE_FARMLAND_UPDATE",
    CITY_FURNITURE_FARMLAND_TOUCH_UI_CLOSED = "CITY_FURNITURE_FARMLAND_TOUCH_UI_CLOSED",
    CITY_FURNITURE_FARMLAND_DUMMY_SEED = "CITY_FURNITURE_FARMLAND_DUMMY_SEED",
    CITY_FURNITURE_FARMLAND_DUMMY_HARVEST = "CITY_FURNITURE_FARMLAND_DUMMY_HARVEST",
    CITY_FURNITURE_FARMLAND_DUMMY_SELECT = "CITY_FURNITURE_FARMLAND_DUMMY_SELECT",
    CITY_FURNITURE_FARMLAND_DUMMY_CANCEL = "CITY_FURNITURE_FARMLAND_DUMMY_CANCEL",
    CITY_FURNITURE_FARMLAND_GROWING_SELECT = "CITY_FURNITURE_FARMLAND_GROWING_SELECTED",
    CITY_FURNITURE_FARMLAND_GROWING_UNSELECT = "CITY_FURNITURE_FARMLAND_GROWING_UNSELECT",

    CITY_FURNITURE_SELECTED_CHANGED = "CITY_FURNITURE_SELECTED_CHANGED",
    CITY_FURNITURE_DOOR_OPEN_STATUS_CHANGED = "CITY_FURNITURE_DOOR_OPEN_STATUS_CHANGED",

    CITY_FURNITURE_STORAGE_COUNT_CHANGE = "CITY_FURNITURE_STORAGE_COUNT_CHANGE",
    CITY_FURNITURE_UPGRADE_START = "CITY_FURNITURE_UPGRADE_START",
    CITY_FURNITURE_UPGRADE_FINISHED = "CITY_FURNITURE_UPGRADE_FINISHED",

    CITY_CITIZEN_WORK_DATA_ADD = 'CITY_CITIZEN_WORK_DATA_ADD',
    CITY_CITIZEN_WORK_DATA_DEL = 'CITY_CITIZEN_WORK_DATA_DEL',
    CITY_CITIZEN_WORK_DATA_CHANGE = 'CITY_CITIZEN_WORK_DATA_CHANGE',
    CITY_CITIZEN_WORK_DATA_REFRESH = 'CITY_CITIZEN_WORK_DATA_REFRESH',
    CITY_CITIZEN_DATA_REFRESH = 'CITY_CITIZEN_DATA_REFRESH',
    CITY_CITIZEN_DATA_HOUSE_NEED_REFRESH = 'CITY_CITIZEN_DATA_HOUSE_NEED_REFRESH',
    CITY_CITIZEN_SELECT_SHOW = 'CITY_CITIZEN_SELECT_SHOW',
    CITY_CITIZEN_MANAGE_UI_STATE = 'CITY_CITIZEN_MANAGE_UI_STATE',
    CITY_CITIZEN_MANAGE_UI_STATE_CLICK = 'CITY_CITIZEN_MANAGE_UI_STATE_CLICK',
    CITY_CITIZEN_SPAWN_CLICK = 'CITY_CITIZEN_SPAWN_CLICK',
    CITY_CITIZEN_FEEDBACK_END_TRIGGER_HUD_EFFECT = "CITY_CITIZEN_FEEDBACK_END_TRIGGER_HUD_EFFECT",
    CITY_CITIZEN_AUTO_COLLECT_TARGET_CHANGED = "CITY_CITIZEN_AUTO_COLLECT_TARGET_CHANGED",
    CITY_CITIZEN_RESOURCE_COLLECT_ACTION_EXIT = "CITY_CITIZEN_RESOURCE_COLLECT_ACTION_EXIT",
    CITY_CITIZEN_IN_USING_POINT_REMOVED = "CITY_CITIZEN_IN_USING_POINT_REMOVED",
    CITY_CITIZEN_ACTION_GROUP_ENTER = "CITY_CITIZEN_ACTION_GROUP_ENTER",
    CITY_CITIZEN_ACTION_GROUP_EXIT = "CITY_CITIZEN_ACTION_GROUP_EXIT",
    CITY_CITIZEN_ACTION_GROUP_MODIFY_INDICATOR = "CITY_CITIZEN_ACTION_GROUP_MODIFY_INDICATOR",

    CITY_EDIT_MODE_PLAY_COMBO_LEVEL_UP = "CITY_EDIT_MODE_PLAY_COMBO_LEVEL_UP",
    CITY_EDIT_MODE_PLAY_COMBO_LEVEL_DOWN = "CITY_EDIT_MODE_PLAY_COMBO_LEVEL_DOWN",
    CITY_EDIT_MODE_CHANGE = "CITY_EDIT_MODE_CHANGE",

    CITY_GESTURE_CLICK = "CITY_CLICK",
    CITY_GESTURE_PRESS_DOWN = "CITY_GESTURE_PRESS_DOWN",
    CITY_GESTURE_TOUCH_START = "CITY_GESTURE_TOUCH_START",

    CITY_STATE_CHANGED = 'CITY_STATE_CHANGED',
    CITY_WARM_UP_FINISH = "CITY_WARM_UP_FINISH",

    CITY_CIRCLE_MENU_CLOSED = "CITY_CIRCLE_MENU_CLOSED",

    CITY_TD_WAVE_START = "CITY_TD_WAVE_START",
    CITY_TD_WAVE_END = "CITY_TD_WAVE_END",

    CITY_ROOT_ALL_LOADER_FINISHED = "CITY_ROOT_ALL_LOADER_FINISHED",

    CITY_SCENE_UI_ITEM_RESUME = "CITY_SCENE_UI_ITEM_RESUME",
    CITY_SCENE_UI_ITEM_HARVEST = "CITY_SCENE_UI_ITEM_HARVEST",

    CITY_SPAWNER_IN_BATTLE_REFRESH = "CITY_SPAWNER_IN_BATTLE_REFRESH",

    ---Creep Clear
    CITY_CREEP_PESTICIDE_START = "CITY_CREEP_PESTICIDE_START",
    CITY_CREEP_PESTICIDE_DRAG = "CITY_CREEP_PESTICIDE_DRAG",
    CITY_CREEP_PESTICIDE_END = "CITY_CREEP_PESTICIDE_END",
    CITY_CREEP_CLEAR_BIG_ADD = "CITY_CREEP_CLEAR_BIG_ADD",
    CITY_CREEP_CLEAR_DO = "CITY_CREEP_CLEAR_DO",
    CITY_CREEP_FORCE_END_DRAG = "CITY_CREEP_FORCE_END_DRAG",
    CITY_CREEP_UI_CLOSE_BY_BUTTON = "CITY_CREEP_UI_CLOSE_BY_BUTTON",
    CITY_CREEP_STATE_CLICK = "CITY_CREEP_STATE_CLICK",

    UI_CITY_CREEP_CLEAR_UI_VFX = "UI_CITY_CREEP_CLEAR_UI_VFX",
    UI_CITY_CREEP_CLEAR_UI_ITEM_COUNT = "UI_CITY_CREEP_CLEAR_UI_ITEM_COUNT",
    UI_CITY_CREEP_CLEAR_UI_UNIT_LIMIT = "UI_CITY_CREEP_CLEAR_UI_UNIT_LIMIT",
    UI_CITY_CREEP_LIMIT_UPDATE = "UI_CITY_CREEP_LIMIT_UPDATE",

    CITY_OPEN_HERO_MEDIATOR_PENDING_RANDOM_VOICE = "CITY_OPEN_HERO_MEDIATOR_PENDING_RANDOM_VOICE",

    CITY_CREEP_FURNITURE_DIRTY = "CITY_CREEP_FURNITURE_DIRTY",

    ---Buliding Upgrade
    CITY_UPGRADE_BUILDING_UI_OPEN = "CITY_UPGRADE_BUILDING_UI_OPEN",
    CITY_UPGRADE_BUILDING_UI_CLOSE = "CITY_UPGRADE_BUILDING_UI_CLOSE",

    UI_CITY_PLACE_FURNITURE_UPDATE_NOFIFICATION = "UI_CITY_PLACE_FURNITURE_UPDATE_NOFIFICATION",

    ---Repair Block
    UI_CITY_REPAIR_BLOCK_CLOSED = "UI_CITY_REPAIR_BLOCK_CLOSED",
    UI_CITY_REPAIR_BLOCK_TRIGGER_OPEN_ANIM = "UI_CITY_REPAIR_BLOCK_TRIGGER_OPEN_ANIM",
    UI_CITY_REPAIR_BLOCK_TRIGGER_CLOSE_ANIM = "UI_CITY_REPAIR_BLOCK_TRIGGER_CLOSE_ANIM",
    CITY_REPAIR_BLOCK_ENTER_STATE = "CITY_REPAIR_BLOCK_ENTER_STATE",
    CITY_REPAIR_BLOCK_EXIT_STATE = "CITY_REPAIR_BLOCK_EXIT_STATE",

    CITY_REPAIR_BLOCK_CREATE = "CITY_REPAIR_BLOCK_CREATE",
    CITY_REPAIR_BLOCK_UPDATE = "CITY_REPAIR_BLOCK_UPDATE",
    CITY_REPAIR_BLOCK_REMOVE = "CITY_REPAIR_BLOCK_REMOVE",
    CITY_REPAIR_BLOCK_BASE_HIGHLIGHT = "CITY_REPAIR_BLOCK_BASE_HIGHLIGHT",
    CITY_REPAIR_BLOCK_WALL_HIGHLIGHT = "CITY_REPAIR_BLOCK_WALL_HIGHLIGHT",
    CITY_REPAIR_BLOCK_BASE_FLASH = "CITY_REPAIR_BLOCK_BASE_FLASH",
    CITY_REPAIR_BLOCK_WALL_FLASH = "CITY_REPAIR_BLOCK_WALL_FLASH",

    CITY_REPAIR_BLOCK_BASE_REPAIR_FINISH = "CITY_REPAIR_BLOCK_BASE_REPAIR_FINISH",
    CITY_REPAIR_BLOCK_WALL_REPAIR_FINISH = "CITY_REPAIR_BLOCK_WALL_REPAIR_FINISH",

    ---Room Walls And Doors
    CITY_BUILDING_ROOM_WALL_UPDATE = "CITY_BUILDING_ROOM_WALL_UPDATE",
    CITY_BUILDING_ROOM_DOOR_UPDATE = "CITY_BUILDING_ROOM_DOOR_UPDATE",
    CITY_ROOM_SELECTION = "CITY_ROOM_SELECTION",
    CITY_ROOM_START_POS = "CITY_ROOM_START_POS",
    CITY_ROOM_UICELL_DRAG_RELEASE = "CITY_ROOM_UICELL_DRAG_RELEASE",
    CITY_ROOM_CANCEL_PLACE = "CITY_ROOM_CANCEL_PLACE",
    CITY_ROOM_DIRTY_FOR_UPGRADE = "CITY_ROOM_DIRTY_FOR_UPGRADE",
    CITY_ROOM_FLOOR_UPDATE = "CITY_ROOM_FLOOR_UPDATE",
    CITY_ROOM_WALL_AND_DOOR_DIRTY = "CITY_ROOM_WALL_AND_DOOR_DIRTY",

    ---Floor And WallPaper
    CITY_FLOOR_SELECTION = "CITY_FLOOR_SELECTION",
    CITY_FLOOR_UICELL_DRAG_RELEASE = "CITY_FLOOR_UICELL_DRAG_RELEASE",
    CITY_FLOOR_ASSET_FLASH = "CITY_FLOOR_ASSET_FLASH",
    CITY_FLOOR_CANCEL_PLACE = "CITY_FLOOR_CANCEL_PLACE",

    ---City SLG
    CITY_SLG_ASSET_UPDATE = "CITY_SLG_ASSET_UPDATE",
    CITY_SLG_HP_UPDATE = "CITY_SLG_HP_UPDATE",
    CITY_SLG_ASSET_ATTACK_TARGET = "CITY_SLG_ASSET_ATTACK_TARGET",
    CITY_SLG_PLAY_SKILL = "CITY_SLG_PLAY_SKILL",

    ---City Batch Update Events
    CITY_BATCH_WDS_CASTLE_BUILDING_UPDATE = "CITY_BATCH_WDS_CASTLE_BUILDING_UPDATE",
    CITY_BATCH_WDS_CASTLE_WORK_UPDATE = "CITY_BATCH_WDS_CASTLE_WORK_UPDATE",
    CITY_BATCH_WDS_CASTLE_FURNITURE_UPDATE = "CITY_BATCH_WDS_CASTLE_FURNITURE_UPDATE",
    CITY_BATCH_WDS_CASTLE_ELEMENT_UPDATE = "CITY_BATCH_WDS_CASTLE_ELEMENT_UPDATE", ---param city City,evtInfo {Event:string, Add:table<number, boolean>, Remove:table<number, boolean>, Change:table<number, boolean>}
    CITY_BATCH_WDS_CASTLE_LEGO_UPDATE = "CITY_BATCH_WDS_CASTLE_LEGO_UPDATE",
    CITY_BATCH_FURNITURE_LEVEL_UP_STATS_CHANGE = "CITY_BATCH_FURNITURE_LEVEL_UP_STATS_CHANGE",
    CITY_BATCH_FURNITURE_LOCK_STATS_CHANGE = "CITY_BATCH_FURNITURE_LOCK_STATS_CHANGE",
    CITY_BATCH_WDS_CASTLE_PET_UPDATE = "CITY_BATCH_WDS_CASTLE_PET_UPDATE", ---param city:City, evtInfo {Event:string, Add:table<number, boolean>, Remove:table<number, boolean>, Change:table<number, boolean>, RelativeFurniture:table<number, number>}

    ---City 7Day Start
    UI_CITY_WORK_PROCESS_SELECT_RECIPE = "UI_CITY_WORK_PROCESS_SELECT_RECIPE", ---制造界面选中配方
    UI_CITY_WORK_PROCESS_QUEUE_MAY_CHANGED = "UI_CITY_WORK_PROCESS_QUEUE_MAY_CHANGED", ---制造界面通知刷新
    UI_CITY_WORK_PRODUCE_OPEN = "UI_CITY_WORK_PRODUCE_OPEN",
    UI_CITY_COLLECT_SELECT_RECIPE = "UI_CITY_COLLECT_SELECT_RECIPE",                        ---派遣采集界面选中配方

    UI_CITY_RES_GEN_SELECT_RECIPE = "UI_CITY_RES_GEN_SELECT_RECIPE", ---种植界面选中配方
    CITY_WORK_UPDATE_TIME = "CITY_WORK_UPDATE_TIME",
    CASTLE_ATTR_UPDATE = "CASTLE_ATTR_UPDATE",

    ---Map Grid
    CITY_MAP_GRID_DEFAULT = "CITY_MAP_GRID_DEFAULT",
    CITY_MAP_GRID_ONLY_SHOW_IN_BUILDING = "CITY_MAP_GRID_ONLY_SHOW_IN_BUILDING",

    CITY_ENVIRONMENTAL_INDICATOR_CHANGE = "CITY_ENVIRONMENTAL_INDICATOR_CHANGE",

    ---I18N
    CITY_CAMERA_TWEEN_TO_TOP_VIEWPORT = "CITY_CAMERA_TWEEN_TO_TOP_VIEWPORT",
    CITY_CAMERA_TWEEN_TO_DEFAULT_VIEWPORT = "CITY_CAMERA_TWEEN_TO_DEFAULT_VIEWPORT",

    ---Furniture Select Camera Action
    CITY_FURNITURE_ENTRY_BUBBLE_LOADED = "CITY_FURNITURE_ENTRY_BUBBLE_LOADED",
    CITY_LOCKED_NONE_SHOWN_NPC_ENTRY_BUBBLE_LOADED = "CITY_LOCKED_NONE_SHOWN_NPC_ENTRY_BUBBLE_LOADED",

    ---Lego
    CITY_LEGO_FLOOR_ADD = "CITY_LEGO_FLOOR_ADD",
    CITY_LEGO_FLOOR_REMOVE = "CITY_LEGO_FLOOR_REMOVE",

    CITY_LEGO_BUILDING_ADD = "CITY_LEGO_BUILDING_ADD",
    CITY_LEGO_BUILDING_REMOVE_PRE = "CITY_LEGO_BUILDING_REMOVE_PRE",
    CITY_LEGO_BUILDING_REMOVE = "CITY_LEGO_BUILDING_REMOVE",
    CITY_LEGO_BUILDING_UPDATE = "CITY_LEGO_BUILDING_UPDATE",
    CITY_LEGO_BUILDING_MOVE = "CITY_LEGO_BUILDING_MOVE",
    CITY_LEGO_BUILDING_RESIZE = "CITY_LEGO_BUILDING_RESIZE",

    CITY_LEGO_BUILDING_SCORE_CHANGE = "CITY_LEGO_BUILDING_SCORE_CHANGE",
    CITY_LEGO_BUILDING_VIEW_POS_CHANGE = "CITY_LEGO_BUILDING_VIEW_POS_CHANGE",

    CITY_LEGO_SHOW_NAME = "CITY_LEGO_SHOW_NAME",
    CITY_LEGO_HIDE_NAME = "CITY_LEGO_HIDE_NAME",

    CITY_SELECTER_ENTER_BUILDING = "CITY_SELECTER_ENTER_BUILDING",
    CITY_SELECTER_LEAVE_BUILDING = "CITY_SELECTER_LEAVE_BUILDING",

    CITY_STATE_TILE_HANDLE_INITIALIZE = "CITY_STATE_TILE_HANDLE_INITIALIZE", --- param CityStateTileHandle
    CITY_STATE_TILE_HANDLE_MOVING = "CITY_STATE_TILE_HANDLE_MOVING", --- param CityStateTileHandle
    CITY_STATE_TILE_HANDLE_ROTATE = "CITY_STATE_TILE_HANDLE_ROTATE", --- param CityStateTileHandle
    CITY_STATE_TILE_HANDLE_RELEASE = "CITY_STATE_TILE_HANDLE_RELEASE", --- param CityStateTileHandle

    CITY_FURNITURE_MAIN_ASSET_LOADED = "CITY_FURNITURE_MAIN_ASSET_LOADED", --- param furnitureId:number, CS.UnityEngine.GameObject
    CITY_FURNITURE_MAIN_ASSET_UNLOAD = "CITY_FURNITURE_MAIN_ASSET_UNLOAD", --- param furnitureId:number

    CITY_PET_DRAMA_LUMBERMILL_COUNTER = "CITY_PET_DRAMA_LUMBERMILL_COUNTER", ---param animatorId:number
    CITY_PET_CLEAR_DISPATCH_VFX_SFX = "CITY_PET_CLEAR_DISPATCH_VFX_SFX", ---param instanceId:number
    CITY_PET_ANIM_EVENT_TRIGGER = "CITY_PET_ANIM_EVENT_TRIGGER", --- param holder:CS.FXAttachPointHolder, param:string

    --- 居民管理UIV3
    UI_CITIZEN_MANAGE_V3_SELECT_PAGE = "UI_CITIZEN_MANAGE_V3_SELECT_PAGE",
    UI_CITIZEN_MANAGE_V3_REFRESH = "UI_CITIZEN_MANAGE_V3_REFRESH",

    ---Furniture Place
    UI_FURNITURE_PLACE_SELECT = "UI_FURNITURE_PLACE_SELECT",
    UI_FURNITURE_PLACE_CLICK_PLACED = "UI_FURNITURE_PLACE_CLICK_PLACED",
    UI_FURNITURE_PLACE_PREVIEW_NEW = "UI_FURNITURE_PLACE_PREVIEW_NEW",
    UI_FURNITURE_PLACE_PREVIEW_FINISH = "UI_FURNITURE_PLACE_PREVIEW_FINISH",

    UI_FURNITURE_MOVING_PREVIEW_BUFF_CHANGE = "UI_FURNITURE_MOVING_PREVIEW_BUFF_CHANGE",
    UI_FURNITURE_MOVING_PREVIEW_END = "UI_FURNITURE_MOVING_PREVIEW_END",

    UI_CITY_LEGO_CLOSE = "UI_CITY_LEGO_CLOSE",
    UI_CITY_LEGO_BUFF_ROUTE_MAP_SELECT_ROOM_TYPE = "UI_CITY_LEGO_BUFF_ROUTE_MAP_SELECT_ROOM_TYPE",
    UI_CITY_LEGO_BUFF_SELECT_CELL = "UI_CITY_LEGO_BUFF_SELECT_CELL",
    UI_CITY_LEGO_BUFF_UPDATE_SELECTED = "UI_CITY_LEGO_BUFF_UPDATE_SELECTED",
    UI_CITY_LEGO_BUFF_RECOMMEND_BUFF_TAG = "UI_CITY_LEGO_BUFF_RECOMMEND_BUFF_TAG",

    UI_CITY_LEGO_SELECT_TARGET_FURNITURE = "UI_CITY_LEGO_SELECT_TARGET_FURNITURE", --- param GuideCall-CfgId, furnitureId
    UI_CITY_LEGO_SELECT_TARGET_FURNITURE_FAILED = "UI_CITY_LEGO_SELECT_TARGET_FURNITURE_FAILED",  --- param GuideCall-CfgId

    UI_MARKER_APPEND = "UI_MARKER_APPEND",
    UI_MARKER_REMOVE = "UI_MARKER_REMOVE",
    UI_MARKER_UPDATE = "UI_MARKER_UPDATE",

    CITY_MAIN_FURNITURE_ADD = "CITY_MAIN_FURNITURE_ADD",
    CITY_MAIN_FURNITURE_REMOVE = "CITY_MAIN_FURNITURE_REMOVE",
    CITY_MAIN_FURNITURE_UPDATE = "CITY_MAIN_FURNITURE_UPDATE",

    ---Touch Menu
    TOUCH_MENU_UPDATE_BASIC = "TOUCH_MENU_UPDATE_BASIC",
    TOUCH_MENU_UPDATE_TABLE_CELL = "TOUCH_MENU_UPDATE_TABLE_CELL",
    TOUCH_MENU_APPEND_TABLE_CELL = "TOUCH_MENU_APPEND_TABLE_CELL",
    TOUCH_MENU_REMOVE_TABLE_CELL = "TOUCH_MENU_REMOVE_TABLE_CELL",
    TOUCH_MENU_UDPATE_GROUP_BTN = "TOUCH_MENU_UDPATE_GROUP_BTN",
    TOUCH_MENU_UDPATE_ALL_GROUP_BTN = "TOUCH_MENU_UDPATE_ALL_GROUP_BTN",
    TOUCH_MENU_SHOW_OVERLAP_DETAIL_PAENL = "TOUCH_MENU_SHOW_OVERLAP_DETAIL_PAENL",
    TOUCH_MENU_HIDE_OVERLAP_DETAIL_PAENL = "TOUCH_MENU_HIDE_OVERLAP_DETAIL_PAENL",

    ---Hud

    HUD_STATE_CHANGED = 'HUD_STATE_CHANGED',
    HUD_PART_SHOW_HIDE_CHANGE = 'HUD_PART_SHOW_HIDE_CHANGE',
    HUD_LOGIC_SHOW_HIDE_CHANGE = 'HUD_LOGIC_SHOW_HIDE_CHANGE',
    HUD_TASK_TEMP_FOLD = "HUD_TASK_TEMP_FOLD",
    HUD_QUERY_ALLIANCE_ENTRY_VIEWPORT = "HUD_QUERY_ALLIANCE_ENTRY_VIEWPORT",
    HUD_QUERY_BOTTOM_RIGHT_FOLD_BTN_VIEWPORT = "HUD_QUERY_BOTTOM_RIGHT_FOLD_BTN_VIEWPORT",
    HUD_HIDE_LAYOUT_BUTTONS = "HUD_CITY_HIDE_LAYOUT_BUTTONS",
    HUD_BLACKBOARD_CHANGED = "HUD_BLACKBOARD_CHANGED",
    HUD_MEDIATOR_RESTARTEND_SHOW = "HUD_MEDIATOR_RESTARTEND_SHOW",
    HUD_TYPE_VISIBLE = "HUD_TYPE_VISIBLE",
    --Kingdom
    SCENE_LOADED = "SCENE_LOADED",
    MY_TROOP_UPDATE = 'MY_TROOP_UPDATE',
    MY_TROOP_CREATED = 'MY_TROOP_CREATED',
    MY_TROOP_DESTROYED = 'MY_TROOP_DESTROYED',
    ON_TROOP_CREATED = 'ON_TROOP_CREATED',
    ON_TROOP_DESTROYED = 'ON_TROOP_DESTROYED',
    ON_TROOP_MOVED        = 'ON_TROOP_MOVED',
    ON_CITY_MONSTER_TROOP_MOVED = 'ON_CITY_MONSTER_TROOP_MOVED',
    MAP_SET_SELECTION = 'MAP_SET_SELECTION',
    MAP_RESET_SELECTION = 'MAP_RESET_SELECTION',
    MAP_SELECT_BUILDING = 'MAP_SELECT_BUILDING',
    MAP_UNSELECT_BUILDING = 'MAP_UNSELECT_BUILDING',
    MAP_CLICK_PET = 'MAP_CLICK_PET',
    MAP_CLICK_REWARD_INTERACTOR = 'MAP_CLICK_REWARD_INTERACTOR',
    MAP_CLICK_ICON = 'MAP_CLICK_ICON',
    MAP_CLICK_ICON_HIGH = 'MAP_CLICK_ICON_HIGH',
    KINGDOM_TRANSITION_START = 'KINGDOM_TRANSITION_START',
    KINGDOM_TRANSITION_START_AFTER_CAPTURE = 'KINGDOM_TRANSITION_START_AFTER_CAPTURE',
    KINGDOM_TRANSITION_END = 'KINGDOM_TRANSITION_END',
    MAP_SELECT_BEHEMOTH_CAGE = 'MAP_SELECT_BEHEMOTH_CAGE',
    TROOP_SIMPLE_MODE_CHANGE = 'TROOP_SIMPLE_MODE_CHANGE',

    ENTER_KINGDOM_MAP_START = 'ENTER_KINGDOM_MAP_START',
    ENTER_KINGDOM_MAP_END = 'ENTER_KINGDOM_MAP_END',
    LEAVE_KINGDOM_MAP_START = 'LEAVE_KINGDOM_MAP_START',
    LEAVE_KINGDOM_MAP_END = 'LEAVE_KINGDOM_MAP_END',
    MAP_TERRAIN_LOADED = 'MAP_TERRAIN_LOADED',
    WAIT_AND_SHOW_UNIT = 'WAIT_AND_SHOW_UNIT',
    WAIT_SHOW_UNIT_CALLBACK = 'WAIT_SHOW_UNIT_CALLBACK',
    CAMERA_LOD_CHANGED = 'LOD_CHANGED',
    CAMERA_SIZE_CHANGED = 'CAMERA_SIZE_CHANGED',
    ON_TROOP_BUILDING_CREATED = 'ON_TROOP_BUILDING_CREATED',
    ON_TROOP_BUILDING_DESTROYED = 'ON_TROOP_BUILDING_DESTROYED',
    ON_CLICK_KINGDOM_TILE = "ON_CLICK_KINGDOM_TILE",
    ON_SELECT_LEFT_TROOP = "ON_SELECT_LEFT_TROOP",
    ON_SLG_START_INTREACTOR = "ON_SLG_START_INTREACTOR",
    ON_SLG_END_ONCE_INTREACTOR = "ON_SLG_END_ONCE_INTREACTOR",
    ON_SLG_END_ALL_INTREACTOR = "ON_SLG_END_ALL_INTREACTOR",
    ON_SLG_BREAK_ALL_INTREACTOR = "ON_SLG_BREAK_ALL_INTREACTOR",
    ON_SLG_MONSTER_DEAD = "ON_SLG_MONSTER_DEAD",
    FIRST_UPDATE_AOI_RECEIVED = "FIRST_UPDATE_AOI_RECEIVED",
    UPDATE_AOI_RECEIVED = "UPDATE_AOI_RECEIVED",
    ON_TROOP_HERO_CHANGED = "ON_TROOP_HERO_CHANGED",
    MAP_FOCUS_BOSS_CHANGED = "MAP_FOCUS_BOSS_CHANGED",
    FOCUS_BOSS_EXECUTE_SKILL = "FOCUS_BOSS_EXECUTE_SKILL",
    CLEAR_SLG_SELECT = "CLEAR_SLG_SELECT",
    --- Territory
    TERRITORY_OCCUPY_CHANGED = "TERRITORY_OCCUPY_CHANGED",

    --- ResourceField
    UI_MAP_RESOURCE_FIELD_COUNT_MAY_CHANGE = "UI_MAP_RESOURCE_FIELD_COUNT_MAY_CHANGE",
    UI_MAP_RESOURCE_FIELD_ADD = "UI_MAP_RESOURCE_FIELD_ADD",
    UI_MAP_RESOURCE_FIELD_DELETE = "UI_MAP_RESOURCE_FIELD_DELETE",
    UI_MAP_RESOURCE_FIELD_UPDATE = "UI_MAP_RESOURCE_FIELD_UPDATE",
    UI_MAP_RESOURCE_FIELD_TRANS_OPTION = "UI_MAP_RESOURCE_FIELD_TRANS_OPTION",

    --Quest
    TASK_DATA_REFRESH = 'TASK_DATA_REFRESH',
    QUEST_SET_FOLLOW = 'QUEST_SET_FOLLOW',
    QUEST_FOLLOW_REFRESH = 'QUEST_FOLLOW_REFRESH',
    QUEST_LATE_UPDATE = 'QUEST_LATE_UPDATE',
    DAILY_ACTIVIEY_CHANGED = 'DAILY_ACTIVIEY_CHANGED',
    RED_POINT_CHANGED = 'RED_POINT_CHANGED',
    HERO_QUEST_ACCEPT_EVENT = 'HERO_QUEST_ACCEPT_EVENT',
    HERO_QUEST_IGNORE_EVENT = 'HERO_QUEST_IGNORE_EVENT',
    HERO_QUEST_ABORT_EVENT = 'HERO_QUEST_ABORT_EVENT',
    QUEST_DATA_WATCHER_EVENT = 'QUEST_DATA_WATCHER_EVENT',
    QUEST_CHAPTER_FINISH = 'QUEST_CHAPTER_FINISH',
    REFRESH_DAILY_QUEST = 'REFRESH_DAILY_QUEST',
    RECORD_DAILY_POS = "RECORD_DAILY_POS",
    RECORD_DEVELOPMENT_POS = "RECORD_DEVELOPMENT_POS",
    ON_QUEST_FINISH = 'ON_QUEST_FINISH',
    REFRESH_HUD_NPC_QUEST = 'REFRESH_HUD_NPC_QUEST',
    QUEST_EVENT_CHAT_NPC_CLICKED = 'QUEST_EVENT_CHAT_NPC_CLICKED',
    QUEST_EVENT_CLEAR_PLAY = 'QUEST_EVENT_CLEAR_PLAY',
    QUEST_SHOW_EXTEND = 'QUEST_SHOW_EXTEND',
    --HUD
    HUD_BOTTOM_RIGHT_EVENT = 'HUD_BOTTOM_RIGHT_EVENT',
    HUD_BOTTOM_RIGHT_SUB_BUTTON_CLICK = 'HUD_BOTTOM_RIGHT_SUB_BUTTON_CLICK',
    HUD_RADAR_FILTER_ITEM = "HUD_RADAR_FILTER_ITEM",
    HUD_CLOSE_TASK_COMP = "HUD_CLOSE_TASK_COMP",
    HUD_COMMUNITY_COMP_SHOW = "HUD_COMMUNITY_COMP_SHOW",
    HUD_COMMUNITY_COMP_HIDE = "HUD_COMMUNITY_COMP_HIDE",
    RADARP_REFRESH_FILTER = "RADARP_REFRESH_FILTER",
    RADAR_STATE_CHANGE = "RADAR_STATE_CHANGE",
    RADAR_HIDE_CLOSE_CAMERA = "RADAR_HIDE_CLOSE_CAMERA",
    RADAR_OPEN_GROUP_INFO = "RADAR_OPEN_GROUP_INFO",
    RADAR_TASK_STATE_CHANGED = "RADAR_TASK_STATE_CHANGED",
    RADAR_TASK_CLICKED = "RADAR_TASK_CLICKED",
    REFRESH_RADAR_TASK = "REFRESH_RADAR_TASK",
    RADAR_TASK_CLAIM_REWARD = "RADAR_TASK_CLAIM_REWARD",
    RADAR_MEDIATOR_OPENED = "RADAR_MEDIATOR_OPENED",
    RADAR_MEDIATOR_CLOSED = "RADAR_MEDIATOR_CLOSED",
    REFRESH_ACTIVITY_NOTICE = "REFRESH_ACTIVITY_NOTICE",
    RADAR_SCOUT_REFRESH = "RADAR_SCOUT_REFRESH",
    RADAR_LEVEL_UP = "RADAR_LEVEL_UP",
    RADAR_UPGRADE_PANEL_CLOSE = "RADAR_UPGRADE_PANEL_CLOSE",
    RADAR_SHOW_NEW_TASK = "RADAR_SHOW_NEW_TASK",
    RADAR_SHOW_REWARD_TASK = "RADAR_SHOW_REWARD_TASK",
    RADAR_MANUAL_TASKS_READY = "RADAR_MANUAL_TASKS_READY",
    RADAR_TRACE_PET_CHANGE = "RADAR_TRACE_PET_CHANGE",
    RADAR_TRACE_PET_SWAP = "RADAR_TRACE_PET_SWAP",
    RADAR_TRACE_PET_START_TRACE = "RADAR_TRACE_PET_START_TRACE",
    
    --Hero
    HERO_DATA_UPDATE = 'HERO_DATA_UPDATE',
    HERO_SELECT_HERO = 'HERO_SELECT_HERO',
    HERO_SELECT_MAINPAGE = 'HERO_SELECT_MAINPAGE',
    HERO_SELECT_TAB = 'HERO_SELECT_TAB',
    HERO_LEVEL_UP = 'HERO_LEVEL_UP',
    HERO_STRENGTH_LEVEL_UP = 'HERO_STRENGTH_LEVEL_UP',
    HERO_UI_CHANGE_CAMERA = 'HERO_UI_CHANGE_CAMERA',
    HERO_BREAK_THROUGH = 'HERO_BREAK_THROUGH',
    HERO_UPGREADE_SKILL = 'HERO_UPGREADE_SKILL',
    HERO_ONCLICK_EQUIP = "HERO_ONCLICK_EQUIP",
    HERO_ONCLICK_DRAWING = "HERO_ONCLICK_DRAWING",
    HERO_ONCLICK_LIST = "HERO_ONCLICK_LIST",
    HERO_SELECT_BUILD = "HERO_SELECT_BUILD",
    OPEN_3D_SHOW_UI= "OPEN_HERO_UI",
    CLOSE_3D_SHOW_UI= "CLOSE_HERO_UI",
    HERO_CARD_SHOW_UI = "HERO_CARD_SHOW_UI",
    CHANGE_CAMERA_STATE = "CHANGE_CAMERA_STATE",
    HERO_CAN_STRENGTH = "HERO_CAN_STRENGTH",
    HERO_CARD_FEED_DRAG_START = "HERO_CARD_FEED_DRAG_START",
    HERO_CARD_FEED_DRAG_HIDE = "HERO_CARD_FEED_DRAG_HIDE",
    HERO_CARD_DOG_INIT = "HERO_CARD_DOG_INIT",
    HERO_CARD_FEED_DRAG_END = "HERO_CARD_FEED_DRAG_END",
    HERO_GET_NEW = "HERO_GET_NEW",
    HERO_ONCLICK_STRENGTHEN = "HERO_ONCLICK_STRENGTHEN",
    HERO_STYLE_FILTER_CLICK = "HERO_STYLE_FILTER_CLICK",

    --TouchInfo
    TOUCH_INFO_UI_CLOSE = "TOUCH_INFO_UI_CLOSE",
    TOUCH_INFO_REWARD_SELECTED = 'TOUCH_INFO_REWARD_SELECTED',

    --Incident
    INCIDENT_INFO_UPDATE = "INCIDENT_INFO_UPDATE",

    --UI
    ON_UIMEDIATOR_OPENED = 'ON_UIMEDIATOR_OPENED',
    ON_UIMEDIATOR_CLOSEED = 'ON_UIMEDIATOR_CLOSEED',
    UI_BUTTON_CLICK_SOUND = 'UI_BUTTON_CLICK_SOUND',
    ON_OVER_UI_ELEMENT = 'ON_OVER_UI_ELEMENT',

    --Shop
    ON_SELECT_SHOP_TAB = "ON_SELECT_SHOP_TAB",
    RECORD_CONTENT_POS = "RECORD_CONTENT_POS",

    --Science
    ON_CLICK_TECH_NODE = "ON_CLICK_TECH_NODE",
    ON_ADD_TECH_STAGE = "ON_ADD_TECH_STAGE",
    ON_REMOVE_TECH_STAGE = "ON_REMOVE_TECH_STAGE",
    ON_REFRESH_TECH_STAGE = "ON_REFRESH_TECH_STAGE",
    ON_REFRESH_TECH_STAGE_WDS = "ON_REFRESH_TECH_STAGE_WDS",
    ON_REFRESH_TECH_RESEARCHING = "ON_REFRESH_TECH_RESEARCHING",
    ON_CLICK_EMPTY = "ON_CLICK_EMPTY",
    ON_FINISH_RESEARCH = "ON_FINISH_RESEARCH",
    ON_CLICK_NEW_CHAPTER = "ON_CLICK_NEW_CHAPTER",
    ON_LOCK_TO_TECH = "ON_LOCK_TO_TECH",
    ON_REFRESH_TECH = "ON_REFRESH_TECH",

    --STORY
    STORY_TIMELINE_ASSET_READY = "STORY_TIMELINE_READY",
    STORY_TIMELINE_START = "STORY_TIMELINE_START",
    STORY_TIMELINE_PAUSE = "STORY_TIMELINE_PAUSE",
    STORY_TIMELINE_STOP = "STORY_TIMELINE_STOP",
    STORY_TIMELINE_DIALOG_NEED_PAUSE = "STORY_TIMELINE_DIALOG_NEED_PAUSE",
    STORY_TIMELINE_GAME_EVENT_START = "STORY_TIMELINE_GAME_EVENT_START",
    STORY_TIMELINE_GAME_EVENT_END = "STORY_TIMELINE_GAME_EVENT_END",
    STORY_TIMELINE_HIDE_CITY_BUBBLE_REFRESH = "STORY_TIMELINE_HIDE_CITY_BUBBLE_REFRESH",
    STORY_TIMELINE_HIDE_CITY_ELEMENTS_REFRESH = "STORY_TIMELINE_HIDE_CITY_ELEMENTS_REFRESH",
    STORY_DIALOG_UI_CLOSED = "STORY_DIALOG_UI_CLOSED",
    STROY_FINISHE_LOG_SERVER_INFO_CHANGED = "STROY_FINISHE_LOG_SERVER_INFO_CHANGED",
    STORY_TIMELINE_UI_CONTROL_SKIP = "STORY_TIMELINE_UI_CONTROL_SKIP",

    --ALLIANCE
    ALLIANCE_JOINED = "ALLIANCE_JOINED",
    ALLIANCE_JOINED_WITH_DATA_READY = "ALLIANCE_JOINED_WITH_DATA_READY",
    ALLIANCE_LEAVED = "ALLIANCE_LEAVED",
    ALLIANCE_RANK_CHANGED = "ALLIANCE_RANK_CHANGED",
    ALLIANCE_BASIC_INFO_CACHE_UPDATE = 'ALLIANCE_BASIC_INFO_CACHE_UPDATE',
    ALLIANCE_MEMBERS_INFO_CACHE_UPDATE = 'ALLIANCE_MEMBERS_INFO_CACHE_UPDATE',
    ALLIANCE_MAPLABLE_CHANGED = "ALLIANCE_MAPLABLE_CHANGED",
    ALLIANCE_NOTICE_COUNT_CHANGED = "ALLIANCE_NOTICE_COUNT_CHANGED",
    ALLIANCE_BATTLE_HUD_REFRESH = "ALLIANCE_BATTLE_HUD_REFRESH",
    ALLIANCE_HELP_REQUESTED = "ALLIANCE_HELP_REQUESTED",
    ALLIANCE_SET_HELP_REQUEST_GREY_TIME = "ALLIANCE_SET_HELP_REQUEST_GREY_TIME",
    ALLIANCE_CACHED_MARK_DATA_CHANGED = "ALLIANCE__CACHED_MARK_DATA_CHANGED",
    ALLIANCE_CACHED_MARK_UNREAD_CHANGE = "ALLIANCE_CACHED_MARK_UNREAD_CHANGE",

    ALLIANCE_BEHEMOTH_ADD = "ALLIANCE_BEHEMOTH_ADD",
    ALLIANCE_BEHEMOTH_UPDATE = "ALLIANCE_BEHEMOTH_UPDATE",
    ALLIANCE_BEHEMOTH_PRE_REMOVE = "ALLIANCE_BEHEMOTH_PRE_REMOVE",
    ALLIANCE_BEHEMOTH_REMOVED = "ALLIANCE_BEHEMOTH_REMOVED",
    ALLIANCE_BEHEMOTH_DEVICE_ADD = "ALLIANCE_BEHEMOTH_DEVICE_ADD",
    ALLIANCE_BEHEMOTH_DEVICE_UPDATE = "ALLIANCE_BEHEMOTH_DEVICE_UPDATE",
    ALLIANCE_BEHEMOTH_DEVICE_PRE_REMOVED = "ALLIANCE_BEHEMOTH_DEVICE_PRE_REMOVED",
    ALLIANCE_BEHEMOTH_DEVICE_REMOVED = "ALLIANCE_BEHEMOTH_DEVICE_REMOVED",
    ALLIANCE_BEHEMOTH_SUMMONER_ADD = "ALLIANCE_BEHEMOTH_SUMMONER_ADD",
    ALLIANCE_BEHEMOTH_SUMMONER_UPDATE = "ALLIANCE_BEHEMOTH_SUMMONER_UPDATE",
    ALLIANCE_BEHEMOTH_SUMMONER_PRE_REMOVED = "ALLIANCE_BEHEMOTH_SUMMONER_PRE_REMOVED",
    ALLIANCE_BEHEMOTH_SUMMONER_REMOVED = "ALLIANCE_BEHEMOTH_SUMMONER_REMOVED",
    ALLIANCE_BEHEMOTH_MOBILE_FORTRESS_ADD = "ALLIANCE_BEHEMOTH_MOBILE_FORTRESS_ADD",
    ALLIANCE_BEHEMOTH_MOBILE_FORTRESS_UPDATE = "ALLIANCE_BEHEMOTH_MOBILE_FORTRESS_UPDATE",
    ALLIANCE_BEHEMOTH_MOBILE_FORTRESS_RPE_REMOVED = "ALLIANCE_BEHEMOTH_MOBILE_FORTRESS_RPE_REMOVED",
    ALLIANCE_BEHEMOTH_MOBILE_FORTRESS_REMOVED = "ALLIANCE_BEHEMOTH_MOBILE_FORTRESS_REMOVED",

    ALLIANCE_CREATION_LANGUAGE_SELECT = "ALLIANCE_CREATION_LANGUAGE_SELECT",
    ALLIANCE_FIND_NEXT_RECRUIT_TOP_INFO = "ALLIANCE_FIND_NEXT_RECRUIT_TOP_INFO",

    ALLIANCE_TASK_CLAIMED = "ALLIANCE_TASK_CLAIMED",
    ALLIANCE_LIMITED_TIME_TASK_CLAIMED = "ALLIANCE_LIMITED_TIME_TASK_CLAIMED",
    ALLIANCE_LEADER_TASK_CLAIMED = "ALLIANCE_LEADER_TASK_CLAIMED",

    --SLG Troop Manager
    SLGTROOP_SOLIDER_NUM_CHANGED = 'SLGTROOP_SOLIDER_NUM_CHANGED',
    SLGTROOP_HERO_CHANGED = 'SLGTROOP_HERO_CHANGED',
    SLGTROOP_PRESET_CHANGED = 'SLGTROOP_PRESET_CHANGED',
    SLGTROOP_SELECTION = 'SLGTROOP_SELECTION',
    SLGTROOP_PATH_CHANGED = 'SLGTROOP_PATH_CHANGED',
    SLGTROOP_WARNING_PUPPET = 'SLGTROOP_WARNING_PUPPET',
    --Trade Popup
    ON_SELECT_TRADE_COST_CELL = "ON_SELECT_TRADE_COST_CELL",
    ON_CHANGE_ITEMS = "ON_CHANGE_ITEMS",

    --HUD Resources
    ON_CHANGE_HUD_RESOURCE_STATE = "ON_CHANGE_HUD_RESOURCE_STATE",

    --JUMP TOAST
    UI_EVENT_JUMP_TOAST_NEW = "UI_EVENT_JUMP_TOAST_NEW",
    UI_EVENT_RUN_TOAST_NEW = "UI_EVENT_RUN_TOAST_NEW",
    UI_EVENT_NOTIFY_POPUP_NEW = "UI_EVENT_NOTIFY_POPUP_NEW",

    COMMON_ITEM_DETAILS_GOTO_CLICK = "COMMON_ITEM_DETAILS_GOTO_CLICK",

    ---Guide
    GUIDE_MASK_SHOW = 'GUIDE_MASK_SHOW',
    ON_UNLOCK_WORLD_FOG = 'ON_UNLOCK_WORLD_FOG',
    ENTER_CITY_TRIGGER = "ENTER_CITY_TRIGGER",
    ON_GUIDE_START = "ON_GUIDE_START",
    ON_GUIDE_END = "ON_GUIDE_END",

    GUIDE_STEP_START = "GUIDE_STEP_START",
    GUIDE_STEP_END = "GUIDE_STEP_END",

    ---GvE
    GVE_BATTLEFIELD_STATE = 'GVE_BATTLEFIELD_STATE',
    GVE_TROOP_MODIFIED = 'GVE_TROOP_MODIFIED',
    GVE_MONSTER_MODIFIED = 'GVE_MONSTER_MODIFIED',
    GVE_CHAT_PANEL_STATE_CHANGED = 'GVE_CHAT_PANEL_STATE_CHANGED',
    GVE_RANK_POP_SHOW_HIDE = 'GVE_RANK_POP_SHOW_HIDE',
    ---Item
    ITEM_COUNT_ALL_CHANGED = "ITEM_COUNT_ALL_CHANGED",

    ---UI打开关闭监听名字
    UI_MEDIATOR_OPENED = "UI_MEDIATOR_OPENED",
    UI_MEDIATOR_CLOSED = "UI_MEDIATOR_CLOSED",

    --Faction
    FACTION_SELECT_TAB = "FACTION_SELECT_TAB",
    FACTION_OPENED = "FACTION_OPENED",
    ON_UNLOCK_CITY_FOG = "ON_UNLOCK_CITY_FOG",

    -- Chat
	CHAT_MESSAGE_UPDATED = "CHAT_MESSAGE_UPDATED",
    CHAT_SESSION_LIST_UPDATED = "CHAT_SESSION_LIST_UPDATED",
    CHAT_GOTO_SESSION = "CHAT_GOTO_SESSION",
    CHAT_SYSTEM_TOAST_CHANGED = "CHAT_SYSTEM_TOAST_CHANGED",
    CHAT_CLOSE_PANEL = "CHAT_CLOSE_PANEL",

    --- Map Explorer List
    MAP_EXPLORER_LIST_MIST_SELECTED = "MAP_EXPLORER_LIST_MIST_SELECTED",
    MAP_EXPLORER_LIST_MIST_CANCELED = "MAP_EXPLORER_LIST_MIST_CANCELED",
    MAP_EXPLORER_LIST_MIST_SCOUT_INFO_CHANGED = "MAP_EXPLORER_LIST_MIST_SCOUT_INFO_CHANGED",

    --- Mist Box
    MIST_BOX_FOUND = "MIST_BOX_FOUND",

    -- Scene
    SCENE_LOAD_STAGE_CHANGED = "SCENE_LOAD_STAGE_CHANGED",

    -- Cloud
    CLOUD_UNCOVER = "CloudUncover",
    HUD_CLOUD_SCREEN_OPEN = "HudCloudScreenOpen",
    HUD_CLOUD_SCREEN_CLOSE = "HudCloudScreenClose",

    -- HUD
    HUD_GOTO_KINGDOM = "HudGotoKingdom",
    HUD_GOTO_MY_CITY = "HudGotoMyCity",
    HUD_RETURN_TO_MY_CITY = "HUD_RETURN_TO_MY_CITY",
    HUD_CLOSE_COIN_TIPS = "HUD_CLOSE_COIN_TIPS",

    -- PerformanceLevelManager
    ENTER_SCENE_QUALITY_CHANGED = "ENTER_SCENE_QUALITY_CHANGED",
    GESTURE_DRAG_START = "GESTURE_DRAG_START",
    GESTURE_DRAG_END = "GESTURE_DRAG_END",

    ON_TROOP_ENTER_EVENT_TRIGGER = 'ON_TROOP_ENTER_EVENT_TRIGGER',
    ON_TROOP_LEAVE_EVENT_TRIGGER = 'ON_TROOP_LEAVE_EVENT_TRIGGER',
    RENDER_FRAME_RATE_SPEEDUP_START = 'RENDER_FRAME_RATE_SPEEDUP_START',
    RENDER_FRAME_RATE_SPEEDUP_END = 'RENDER_FRAME_RATE_SPEEDUP_END',
    RENDER_FRAME_RATE_OVERRIDE = 'RENDER_FRAME_RATE_OVERRIDE',

	-- UIPetSelectPopupComponent
	ON_UI_PET_SELECT_POPUP_COMPONENT_CLOSE = 'ON_UI_PET_SELECT_POPUP_COMPONENT_CLOSE',

    -- Loading
    ENTER_POST_INIT_DATA_STATE = 'ENTER_POST_INIT_DATA_STATE',
    LANGUAGE_AND_CONFIGS_READY = 'EXIT_SYNC_LANGUAGE_STATE',

    -- 支付
    PAY_SUCCESS = 'PAY_SUCCESS',
    -- PAY_SUCCESS_WITH_GAME_ITEM_OR_FREE = 'PAY_SUCCESS_WITH_GAME_ITEM_OR_FREE',

    --WorldEventRecord
    WORLD_EVENT_CHANGEED = 'WORLD_EVENT_CHANGEED',
    WORLD_EVENT_RECORD_UI_STATE_CHANGEED = 'WORLD_EVENT_RECORD_UI_STATE_CHANGEED',


    --WorldEvent
    WORLD_EVENT_PROGRESS_DOT = "WORLD_EVENT_PROGRESS_DOT",
    WORLD_EVENT_CLICK_ALLIANCE_REWARD = "WORLD_EVENT_CLICK_ALLIANCE_REWARD",
    WORLD_EVENT_SHOW_HIDE = "WORLD_EVENT_SHOW_HIDE",
    WORLD_EVENT_FINISH = "WORLD_EVENT_FINISH",
    WORLD_EVENT_PROGRESS = "WORLD_EVENT_PROGRESS",
    SET_WORLD_EVENT_TOAST_STATE = 'SET_WORLD_EVENT_TOAST_STATE',
    WORLD_EVENT_PRE_NOTICE_STATE_END = 'WORLD_EVENT_PRE_NOTICE_STATE_END',
    MAP_CLICK_WORLD_EVENT = 'MAP_CLICK_WORLD_EVENT',
    CHANG_TOAST_SHOW_TYPE = 'CHANG_TOAST_SHOW_TYPE',
    CHANG_SEARCH_PANEL_STATE = "CHANG_SEARCH_PANEL_STATE",
    WORLD_EVENT_TOAST_OPEN = "WORLD_EVENT_TOAST_OPEN",
    ALLIANCE_WORLD_EVENT_DEAD = "ALLIANCE_WORLD_EVENT_DEAD",

    MAP_CLICK_MONSTER = 'MAP_CLICK_MONSTER',

    --ActivityShop
    ON_SELECT_ACTIVITY_TAB = "ON_SELECT_ACTIVITY_TAB",
    ON_CREATE_CHILD = "ON_CREATE_CHILD",
    ON_SELECT_CUSTOM_PACK = "ON_SELECT_CUSTOM_PACK",
    ON_SELECT_CUSTOM_ITEM = "ON_SELECT_CUSTOM_ITEM",

    ON_CREATE_POPUP_CHILD = "ON_CREATE_POPUP_CHILD",
    ON_SELECT_POPUP_TAB = "ON_SELECT_POPUP_TAB",
    ON_ACT_POPUP_LIST_CHANGE = "ON_ACT_POPUP_LIST_CHANGE",

	-- SE
	SE_START_LOADING = "SE_START_LOADING",
    SE_EXIT = "SE_EXIT",
    SE_TIMELINE_START = "SE_TIMELINE_START",
    SE_TIMELINE_END = "SE_TIMELINE_END",
    SE_HUD_OPENED = "SE_HUD_OPENED",
    SE_REQUEST_CITY_ENTER_BATTLE = "SE_REQUEST_CITY_ENTER_BATTLE",
    SE_REQUEST_CITY_LEAVE_BATTLE = "SE_REQUEST_CITY_LEAVE_BATTLE",
    SE_UNIT_HERO_CREATE = "SE_UNIT_HERO_CREATE",
    SE_UNIT_HERO_DESTORY = "SE_UNIT_HERO_DESTORY",
    SE_UNIT_PET_CREATE = "SE_UNIT_PET_CREATE",
    SE_UNIT_PET_DESTORY = "SE_UNIT_PET_DESTORY",

    SE_JOYSTICK_POINTER_DOWN = "SE_JOYSTICK_POINTER_DOWN",          ---摇杆按下, params:[1] joystickId:number
    SE_JOYSTICK_POINTER_UP = "SE_JOYSTICK_POINTER_UP",              ---摇杆抬起, params:[1] joystickId:number
    SE_JOYSTICK_POINTER_CANCEL = "SE_JOYSTICK_POINTER_CANCEL",      ---放弃摇杆操作, params:[1] joystickId:number
    SE_JOYSTICK_VALUE_CHANGED = "SE_JOYSTICK_VALUE_CHANGED",        ---摇杆拖拽期间, params:[1] joystickId:number, [2] dir: CS.UnityEngine.Vector2, [3]inCancelRange:boolean|nil
    SE_JOYSTICK_VALUE_CLEAR = "SE_JOYSTICK_VALUE_CLEAR",            ---UI关闭，销毁所有缓存的摇杆数据, params[...]: joystickId:number

	-- Troop Edit
	TROOP_EDIT_REFRESH_POWER = "TROOP_EDIT_REFRESH_POWER",
    TROOP_PET_CLICK = "TROOP_PET_CLICK",
    ON_TROOP_MODEL_DRAG_START = "ON_TROOP_MODEL_DRAG_START",
    ON_TROOP_MODEL_DRAG_END = "ON_TROOP_MODEL_DRAG_END",
    ON_TROOP_MODEL_CLICK = "ON_TROOP_MODEL_CLICK",
    ON_TROOP_CLICK_EMPTY = "ON_TROOP_CLICK_EMPTY",
    CMD_TROOP_EDIT_CLOSE = "CMD_TROOP_EDIT_CLOSE",
    TROOP_HINT_TOGGLED = "TROOP_HINT_TOGGLED",
    ON_TROOP_MEDIATOR_ADD_HP = "ON_TROOP_MEDIATOR_ADD_HP",
    ON_TROOP_HP_VX_MOVE_TO_TARGET = "ON_TROOP_HP_VX_MOVE_TO_TARGET",
    ON_TROOP_SLOT_DRAG_MOVE_IN = "ON_TROOP_SLOT_DRAG_MOVE_IN",
    ON_TROOP_SLOT_DRAG_MOVE_OUT = "ON_TROOP_SLOT_DRAG_MOVE_OUT",
    ON_DEPLOY_VFX_LOADED = "ON_DEPLOY_VGX_LOADED",
    ON_LOCKED_SLOT_RING_LOADED = "ON_LOCKED_SLOT_RING_LOADED",
    ON_TROOP_SLOT_CLICK = "ON_TROOP_SLOT_CLICK",

	-- Pet
	PET_LEVEL_UP = "PET_LEVEL_UP",
    ON_PET_LEVEL_UP = "ON_PET_LEVEL_UP",
    ON_PET_ADD = "ON_PET_ADD",
    ON_PET_REMOVE = "ON_PET_REMOVE",
    HERO_PET_CARRY = "HERO_PET_CARRY",
    HERO_PET_CANCEL = "HERO_PET_CANCEL",
    FORCE_HIDE_PET_REDDOT_TROOP = "FORCE_HIDE_PET_REDDOT_TROOP",
    PET_COLLECTION_TAB = "PET_COLLECTION_TAB",
    PET_COLLECTION_DETAIL_TAB = "PET_COLLECTION_DETAIL_TAB",
    PET_COLLECTION_DETAIL_LOCK_TAB = "PET_COLLECTION_DETAIL_LOCK_TAB",
    PET_COLLECTION_STORY_RED_POINT = "PET_COLLECTION_STORY_RED_POINT",
    PET_COLLECTION_CLAIM_REWARDS = "PET_COLLECTION_CLAIM_REWARDS",
    PET_COLLECTION_RESEARCH_COMPLETE = "PET_COLLECTION_RESEARCH_COMPLETE",
    PET_REFRESH_UNLOCK_ITEM = "PET_REFRESH_UNLOCK_ITEM",
    PET_REFRESH_UNLOCK_STATE = "PET_REFRESH_UNLOCK_STATE",
    PET_STRENGTN_UP = "PET_STRENGTN_UP",
    PET_BREAK_UP = "PET_BREAK_UP",
    PET_LEARN_SKILL = "PET_LEARN_SKILL",
    PET_UPGRADE_SKILL = "PET_UPGRADE_SKILL",
    PET_UPGRADE_SKILL_COMPLETE = "PET_UPGRADE_SKILL_COMPLETE",
    PET_EQUIP_SKILL = "PET_EQUIP_SKILL",
    PET_UNEQUIP_SKILL = "PET_UNEQUIP_SKILL",
    PET_UI_MAIN_REFRESH = "PET_UI_MAIN_REFRESH",
    PET_UI_MAIN_REFRESH_MODEL = "PET_UI_MAIN_REFRESH_MODEL",
    PET_RENAME = "PET_RENAME",
    PET_REFRESH_SELECT = "PET_REFRESH_SELECT",
	-- Mail
	MAIL_REFRESH = "MAIL_REFRESH",
    MAIL_REPORT_RECEIVED = "MAIL_REPORT_RECEIVED",

    WORLD_SEARCH_TYPE = "WORLD_SEARCH_TYPE",

    -- NoviceTask
    ON_SELECT_NOVICE_TASK_TAB = "ON_SELECT_NOVICE_TASK_TAB",
    ON_SELECT_NOVICE_TASK_SUB_TAB = "ON_SELECT_NOVICE_TASK_SUB_TAB",
    ON_NOVICE_REDDOT_UPDATE = "ON_NOVICE_REDDOT_UPDATE",

	-- Reward Video
	REWARD_VIDEO_FINISH = "RewardVideoFinish",

    UI_WORLD_CONQUER_FAIL_TIP_NEW = "UI_WORLD_CONQUER_FAIL_TIP_NEW",
    UI_POWER_TOAST_REFRESH = "UI_POWER_TOAST_REFRESH",
    HUD_PLAY_POWER_EFFECT = "HUD_PLAY_POWER_EFFECT",

    HUD_SELECT_TROOP_ASSEMBLE_TIME_PREFETCH_UPDATE = "HUD_SELECT_TROOP_ASSEMBLE_TIME_PREFETCH_UPDATE",
    HUD_SELECT_TROOP_ASSEMBLE_TIME_PREFETCH_UPDATE_FAILED = "HUD_SELECT_TROOP_ASSEMBLE_TIME_PREFETCH_UPDATE_FAILED",

    ALLIANCE_WAR_INFO_REMOVED = "ALLIANCE_WAR_INFO_REMOVED",

    ALLIANCE_TECH_NODE_UPDATED = "ALLIANCE_TECH_NODE_UPDATED",
    ALLIANCE_TECH_RECOMMEND_UPDATED = "ALLIANCE_TECH_RECOMMEND_UPDATED",
    ALLIANCE_TECH_RESEARCH_IDLE_STATUS_UPDATED = "ALLIANCE_TECH_RESEARCH_IDLE_STATUS_UPDATED",
    ALLIANCE_TECH_CAN_UP_GROUP_REFRESH = "ALLIANCE_TECH_CAN_UP_GROUP_REFRESH",
    ALLIANCE_TERRITORY_DAILY_GIFT_REDDOT = "ALLIANCE_TERRITORY_DAILY_GIFT_REDDOT",

    UI_ALLIANCE_TECH_GROUP_SELECTED = "UI_ALLIANCE_TECH_GROUP_SELECTED",
    UI_ALLIANCE_TECH_FOCUS_ON_GROUP = "UI_ALLIANCE_TECH_FOCUS_ON_GROUP",
    UI_ALLIANCE_TECH_CURRENCY_UPDATE = "UI_ALLIANCE_TECH_CURRENCY_UPDATE",

    ALLIANCE_CURRENCY_UPDATED_IDS = "ALLIANCE_CURRENCY_UPDATED_IDS",
    ALLIANCE_CURRENCY_UPDATED_TYPES = "ALLIANCE_CURRENCY_UPDATED_TYPES",

    BUBBLE_IN_MIST = "BUBBLE_IN_MIST",

    --- 刷新内城环形菜单
    UI_REFRESH_CITY_CIRCLE_MENU = "UI_REFRESH_CITY_CIRCLE_MENU",

    -- Se Climb Tower
    SE_CLIMB_TOWER_CHAPTER_CLICK = 'SE_CLIMB_TOWER_CHAPTER_CLICK',
    SE_CLIMB_TOWER_SECTION_CLICK = 'SE_CLIMB_TOWER_SECTION_CLICK',
    SE_CLIMB_TOWER_RETURN_TO_CHAPTER = 'SE_CLIMB_TOWER_RETURN_TO_CHAPTER',
    SE_CLIMB_TOWER_STAR_REWARD_BOX_SHOW_TIPS = 'SE_CLIMB_TOWER_STAR_REWARD_BOX_CLICK',

    --- 采集奖励弹出
    UI_REWARD_RESOURCE_POPUP = "UI_REWARD_RESOURCE_POPUP",
    -- Activity Center
    ON_CREATE_ACT_CHILD = "ON_CREATE_ACT_CHILD",
    ON_SELECT_ACTIVITY_CENTER_TAB = "ON_SELECT_ACTIVITY_CENTER_TAB",

    -- Leaderboard
    LEADERBOARD_TAB_MAIN_CLICK = 'LEADERBOARD_TAB_MAIN_CLICK',
    LEADERBOARD_TAB_SUB_CLICK = 'LEADERBOARD_TAB_SUB_CLICK',

    --WorldTrend
    WORLD_TREND_SELECT_DOT = "WORLD_TREND_SELECT_DOT",
    WORLD_TREND_REWARD = "WORLD_TREND_REWARD",
    WORLD_TREND_STATE_CHANGED = "WORLD_TREND_STATE_CHANGED",

    --LuaStateMachineBehaviour LuaStateMachineBehaviourParameter
    LuaStateMachineBehaviour = "LuaStateMachineBehaviour",

    --Hunting
    HUNTING_MONSTER_CELL_SELECT = "HUNTING_MONSTER_CELL_SELECT",
    HUNTING_GOTO_CURRENT_LEVEL = "HUNTING_GOTO_CURRENT_LEVEL",

    KINGDOM_BUILDING_SLG_BATTLE_STATE = "KINGDOM_BUILDING_SLG_BATTLE_STATE",
    KINGDOM_BUILDING_SLG_ATTACK_STATE = "KINGDOM_BUILDING_SLG_ATTACK_STATE",
    KINGDOM_BUILDING_SLG_PLAY_ANIM = "KINGDOM_BUILDING_SLG_PLAY_ANIM",

    --SystemEntry
    SYSTEM_ENTRY_OPEN = "SYSTEM_ENTRY_OPEN",
    KINGDOM_SYSTEM_ENTRY_REFRESH = "KINGDOM_SYSTEM_ENTRY_REFRESH",

    --Relocate
    RELOCATE_CITY_DONE = "RELOCATE_CITY_DONE",

    --BattlePass
    BATTLEPASS_REWARD_CELL_SHOW_HIDE = "BATTLEPASS_REWARD_CELL_SHOW_HIDE",
    BATTLEPASS_TASK_REWARD_CLAIM = "BATTLEPASS_TASK_REWARD_CLAIM",
    BATTLEPASS_REWARD_CLAIM = "BATTLEPASS_REWARD_CLAIM",
    BATTLEPASS_UNLOCK_VIP_OPEN = "BATTLEPASS_UNLOCK_VIP_OPEN",
    BATTLEPASS_UNLOCK_VIP_CLOSE = "BATTLEPASS_UNLOCK_VIP_CLOSE",

    --ChooseToggle
    CHOOSE_TOGGLE_DOT_CLICK = "CHOOSE_TOGGLE_DOT_CLICK",

    PLAYER_CUSTOM_ICON_READY = "PLAYER_CUSTOM_ICON_READY",

    --ActivityAllianceBossRegister
    ON_ACTIVITY_ALLIANCE_BOSS_REGISTER_TIME_SELCET = "ON_ACTIVITY_ALLIANCE_BOSS_REGISTER_TIME_SELCET",
    ON_ACTIVITY_ALLIANCE_BOSS_REGISTER_BEHEMOTH_CELL_SELECT = "ON_ACTIVITY_ALLIANCE_BOSS_REGISTER_BEHEMOTH_CELL_SELECT",
    ON_ACTIVITY_BEHEMOTH_CELL_SELECT = "ON_ACTIVITY_BEHEMOTH_CELL_SELECT",

    --EarthRevival
    ON_EARTH_REVIVAL_TASK_DAY_SELECT = "ON_EARTH_REVIVAL_TASK_DAY_SELECT",
    ON_EARTH_REVIVAL_NEWS_CELL_CLICK = "ON_EARTH_REVIVAL_NEWS_CELL_CLICK",
    ON_EARTH_REVIVAL_ACTIVITY_CELL_CLICK = "ON_EARTH_REVIVAL_ACTIVITY_CELL_CLICK",
    ON_DAILY_REWARD_CLAIMED = "ON_DAILY_REWARD_CLAIMED",
    UPDATE_WORLD_TREND_STAGE_REWARD = "UPDATE_WORLD_TREND_STAGE_REWARD",
    ON_FIRE_PLAN_BTN_SHOP_CLICK = "ON_FIRE_PLAN_BTN_SHOP_CLICK",
    ON_FIRE_PLAN_TASK_LINK_FINISH = "ON_FIRE_PLAN_TASK_LINK_FINISH",

    --Landform
    OPEN_LANDFORM_VIEW = "OPEN_LANDFORM_VIEW",
    ON_LANDFORM_SELECT = "ON_LANDFORM_SELECT",
    ENTER_COMMUNICATION_MODE = "ENTER_COMMUNICATION_MODE",
    LANDFORM_DISPLAY_MODE_CHANGE = "LANDFORM_DISPLAY_MODE_CHANGE",

    --CustomHexChunk
    KINGDOM_CUSTOM_HEX_CHUNK_SHOW = "KINGDOM_CUSTOM_HEX_CHUNK_SHOW",
    KINGDOM_CUSTOM_HEX_CHUNK_PRE_HIDE = "KINGDOM_CUSTOM_HEX_CHUNK_PRE_HIDE",
    KINGDOM_CUSTOM_HEX_CHUNK_HIDE = "KINGDOM_CUSTOM_HEX_CHUNK_HIDE",

    --AutoPetCatch
    AUTO_PET_CATCH_STATE_CHANGED = "AUTO_PET_CATCH_STATE_CHANGED",

    --ALLIANCE_RECOMMENDATION_CHANGED
    ALLIANCE_RECOMMENDATION_CHANGED = "ALLIANCE_RECOMMENDATION_CHANGED",

    --Radar
    STOP_TASK_AUTO_FINGER = "STOP_TASK_AUTO_FINGER",
    RADAR_FURNITURE_CHANGED = "RADAR_FURNITURE_CHANGED",
    --GetMore
    EXCHANGE_RESOURCE_SELECT_ITEM = "EXCHANGE_RESOURCE_SELECT_ITEM",

    SE_EXPLORER_HERO_CAN_UPGRADE_CHECK = "SE_EXPLORER_HERO_CAN_UPGRADE_CHECK",
    SE_EXPLORER_PET_CAN_UPGRADE_CHECK = "SE_EXPLORER_PET_CAN_UPGRADE_CHECK",
    SE_BATTLE_SPEED_REFRESH = "SE_BATTLE_SPEED_REFRESH",

    SLG_UNDER_ATTACK_WARNING = "SLG_UNDER_ATTACK_WARNING",

    UNIT_MARKER_CANVAS_SHOW_HIDE_FOR_3D_UI = "UNIT_MARKER_CANVAS_SHOW_HIDE_FOR_3D_UI",

    --PVP
    REPLICA_PVP_CHALLENGE_CLICK = "REPLICA_PVP_CHALLENGE_CLICK",

    --Hero Rescue
    HERO_RESCUE = "HERO_RESCUE",
    UI_HERO_RESCUE_SHOW = "UI_HERO_RESCUE_SHOW",
    UI_HERO_RESCUE_SHOW_HIDE_BUBBLE = "UI_HERO_RESCUE_SHOW_HIDE_BUBBLE",
    UI_HERO_RESCUE_FIRST_TIME_SHOW_BUBBLE = "UI_HERO_RESCUE_FIRST_TIME_SHOW_BUBBLE",

    --Land Explore
    LAND_EXPLORE_REWARD_CLAIM = "LAND_EXPLORE_REWARD_CLAIM",

    --UI Async
    UI_ASYNC_QUEUE_END = "UI_ASYNC_QUEUE_END",
}

---@class LuaStateMachineBehaviourParameter
---@field instanceId number
---@field eventId number @CS.AnimatorEvent Enter=0,Exit=1
---@field layerIndex number
---@field stringParam string
---@field numberParam number

return EventConst

