---@class GuideConst
local GuideConst = {
    CallID = {
        MainbaseFinish = 2,
        EnterCity = 3,
        EnterKingdom = 4,
        BuildingFinish = 5,
        SetupFurniture = 6,
        ChapterQuestFinish = 7,
        OpenUIHeroMainMediator = 8,
        ChapterQuestStoryFinish = 9,
        SEHudTroopShow = 10,
        AfterCreepSprayMedicine = 11,
        AfterCreepSweep = 12,
        CollectExit = 13,
        FactionOpen = 14,
        UnlockFog = 15,
        NpcClick = 18,
        OpenRadar = 21,
        FindMapMonster1 = 22,
        FindMapMonster2 = 23,
        FindMapMonster3 = 24,
        FindMapMonster4 = 25,
        FindMapMonster5 = 26,
        RadarReward = 27,
        OpenUIHeroEquipForgeRoomUIMediator = 28,
        SlgMonsterDead = 29,
        PetCaptureFinish = 32,
        PetCaptureStart = 34,
        LandformPetGuide = 37,
        SelectBehemothCage = 38,
        AllianceLeaderAttackVillage = 41,
        TroopInjured = 47,
        AllianceLeaderFirstGuide = 48,
        EnterCitySeExploreMode = 49,
        PetLevelUp = 50,
        MainFurnitureUpgradeStart = 51,
        CityWallUpgradeStart = 53,
        TurtleUpgradeStart = 54,
        HotSpringUpgradeStart = 55,
        OnCityExploreZoneRecoveryAnimEnd = 56,
        FirstTimeJoinAlliance = 57,
        JoinAlliance = 58,
        HudLandformStart = 1057,
        HudLandformCommunication = 5276,
        TroopEditorGuide = 5288,
        SelectMonster = 6223,
        SelectResource = 6224,
        SelectSE = 6225,
        SelectPet = 6226,
        SelectEvent = 6227,
        SelectRewardBox = 6228,
        SelectStronghold = 6229,
    },
    GroupID = {
        FristEnterCity = 103,
    },
    TargetTypeEnum = {
        WorldPos = 1,
        ScreenPos = 2,
        UITrans = 11,
        CityTile = 12,
        Troop = 13,
        Transform = 14,
        Mob = 15,
    }
}


return GuideConst