---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shoufeng.zhang.
--- DateTime: 2022/6/13 18:55
---
---@abstract
---@class UIMediatorProcessor
local UIMediatorProcessor = class('UIMediatorProcessor')

---@param uiMediator CS.DragonReborn.UI.UIMediator
function UIMediatorProcessor:PreProcessOnCreate(uiMediator)
   --override this    
end
---PreProcessOnShow
---@param uiMediator CS.DragonReborn.UI.UIMediator
function UIMediatorProcessor:PreProcessOnShow(uiMediator)
   --override this    
end
---PreProcessOnOpened
---@param uiMediator CS.DragonReborn.UI.UIMediator
function UIMediatorProcessor:PreProcessOnOpened(uiMediator)
   --override this    
end
---PreProcessOnHide
---@param uiMediator CS.DragonReborn.UI.UIMediator
function UIMediatorProcessor:PreProcessOnHide(uiMediator)
   --override this    
end
---PreProcessOnClose
---@param uiMediator CS.DragonReborn.UI.UIMediator
---@param param table
function UIMediatorProcessor:PreProcessOnClose(uiMediator,param)
   --override this    
end
---PostProcessOnCreate
---@param uiMediator CS.DragonReborn.UI.UIMediator
function UIMediatorProcessor:PostProcessOnCreate(uiMediator)
   --override this    
end
---PostProcessOnShow
---@param uiMediator CS.DragonReborn.UI.UIMediator
function UIMediatorProcessor:PostProcessOnShow(uiMediator)
   --override this    
end
---PostProcessOnOpened
---@param uiMediator CS.DragonReborn.UI.UIMediator
function UIMediatorProcessor:PostProcessOnOpened(uiMediator)
   --override this    
end
---PostProcessOnHide
---@param uiMediator CS.DragonReborn.UI.UIMediator
function UIMediatorProcessor:PostProcessOnHide(uiMediator)
   --override this    
end
---PostProcessOnClose
---@param uiMediator CS.DragonReborn.UI.UIMediator
---@param param table
function UIMediatorProcessor:PostProcessOnClose(uiMediator,param)
   --override this    
end
---OnProcessorRemove
---@param uiMediator CS.DragonReborn.UI.UIMediator
function UIMediatorProcessor:OnProcessorRemove(uiMediator)
   --override this    
end


return UIMediatorProcessor