---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiang.li
--- DateTime: 2021/7/26 10:19
---
local SEUnitType = require("SEUnitType")
local SEUnit = require("SEUnit")

---@class SEMonster:SEUnit
---@field new fun(manager:SEUnitManager, id:number, data:SEUnitData):SEMonster
---@field super SEUnit
local SEMonster = class("SEMonster",  SEUnit);

---@param self SEMonster
---@param manager SEUnitManager
---@param id number
---@param data SEUnitData
---@return void
function SEMonster:ctor(manager, id, data)
    SEMonster.super.ctor(self, manager, id, SEUnitType.Monster)

    local SEUnitController = require("SEUnitController")
    local SEActor = require("SEActor")
    local SEUnitRenderer = require("SEUnitRenderer")
    local SEUnitStateMachine = require("SEUnitStateMachine")
    local SEUnitLocomotion = require("SEUnitLocomotion")
    self.m_actor = SEActor.new(self)
    data:SetUnit(self)
    self:AddComponent(data)
    self:AddComponent(SEUnitRenderer.new(self))
    self:AddComponent(SEUnitStateMachine.new(self))
    self:AddComponent(SEUnitLocomotion.new(self))
    self:AddComponent(SEUnitController.new(self))
end

return SEMonster
