---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shoufeng.zhang.
--- DateTime: 2022/2/17 21:08
---
---@class PageBaseState
---@field module QuestModule_Chapter
---@field viewer ChapterQuestPageComponent
---@field fsm PageStateCtrl
local PageBaseState = class('PageBaseState')

function PageBaseState:ctor(module,viewer,stateMachine)
    self.module = module
    self.viewer = viewer
    self.fsm = stateMachine
end

function PageBaseState.GetName()
    return 'PageBaseState'
end

function PageBaseState:In(data)

end


function PageBaseState:Out(data)

end

function PageBaseState:Next(data,prev)

end

function PageBaseState:SetViewer(viewer)
    self.viewer = viewer
end

function PageBaseState:Refresh()

end


return PageBaseState