---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shoufeng.zhang.
--- DateTime: 2022/2/20 16:45
--- filename: QuestStateConstant.lua.txt
---

local StateName = {
    Init                    = 'PageState_Init',
    -- ChapterStart            = 'PageState_ChapterStart',
    PartNormal              = 'PageState_PartNormal',
    PartComplete            = 'PageState_PartComplete',
    GroupComplete           = 'PageState_GroupComplete',
    QuestClaim              = 'PageState_QuestClaim',
    AllFinish               = 'PageState_AllFinish',
}

local StateCmd = {
    NextState = 'Next',
    QuestReward = 'RequestChapterQuestReward',
    PartReward = 'PartReward',
    PartEndStory = 'PartEndStory',
    NextPart = 'NextPart',
    ChapterGroupReward = 'ChapterTargetReward',
}

return {
    StateCmd = StateCmd,
    StateName = StateName
}