---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xh.
--- DateTime: 2022/7/22 10:14
---

local BaseUIComponent = require('BaseUIComponent')

---@class TouchInfoImageCompData
---@field front string
---@field background string

---@class TouchInfoImageComponent : BaseUIComponent
local TouchInfoImageComponent = class("TouchInfoImageComponent", BaseUIComponent)

function TouchInfoImageComponent:OnCreate()
    self._p_img_front = self:Image("p_img_front")
    self._p_img_back = self:Image("p_img_back")
end

---@param data TouchInfoImageCompData
function TouchInfoImageComponent:OnFeedData(data)
    self._p_img_front.gameObject:SetActive(data.front ~= nil)
    if data.front then
        g_Game.SpriteManager:LoadSprite(data.front, self._p_img_front)
    end
    self._p_img_back.gameObject:SetActive(data.background ~= nil)
    if data.background then
        g_Game.SpriteManager:LoadSprite(data.background, self._p_img_back)
    end
end

return TouchInfoImageComponent