---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xh.
--- DateTime: 2022/7/22 11:52
---

local BaseUIComponent = require('BaseUIComponent')
local Delegate = require("Delegate")

---@class TouchInfoPairComponentData
---@field icon string
---@field name string
---@field content string|fun():string
---@field needTick boolean
---@field backState number

---@class TouchInfoPairComponent : BaseUIComponent
local TouchInfoPairComponent = class("TouchInfoPairComponent", BaseUIComponent)

function TouchInfoPairComponent:OnCreate()
    self._p_icon_item = self:Image("p_icon_item")
    self._p_text_item_name = self:Text("p_text_item_name")
    self._p_text_item_content = self:Text("p_text_item_content")

    self._p_base_01 = self:GameObject("p_base_01")
    self._p_base_02 = self:GameObject("p_base_02")
end

---@param data TouchInfoPairComponentData
function TouchInfoPairComponent:OnFeedData(data)
    if type(data.icon) == "string" then
        self._p_icon_item.gameObject:SetActive(true)
        g_Game.SpriteManager:LoadSprite(data.icon, self._p_icon_item)
    else
        self._p_icon_item.gameObject:SetActive(false)
    end

    self._p_text_item_name.text = data.name

    if type(data.content) == "string" then
        self._p_text_item_content.text = data.content
    elseif type(data.content) == "function" then
        self._p_text_item_content.text = data.content()
    end

    self._p_base_01:SetActive(data.backState == 1)
    self._p_base_02:SetActive(data.backState == 2)

    if data.needTick then
        self.contentFunc = data.content
        g_Game:AddSecondTicker(Delegate.GetOrCreate(self, self.OnTick))
    end
end

function TouchInfoPairComponent:OnTick()
    if type(self.contentFunc) == "function" then
        self._p_text_item_content.text = self.contentFunc()
    end
end

function TouchInfoPairComponent:OnClose()
    if self.contentFunc then
        g_Game:RemoveSecondTicker(Delegate.GetOrCreate(self, self.OnTick))
        self.contentFunc = nil
    end
end

return TouchInfoPairComponent