---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shoufeng.zhang.
--- DateTime: 2022/5/12 16:15
---

local SlgLocalConfig = {}

SlgLocalConfig.FloatingTextValueType = 
{
    String = 0,
    Number = 1,
}

--部队统一缩放，与服务器同步设置
SlgLocalConfig.TroopUniScale = 4
SlgLocalConfig.TroopRadiusOffset = 0.05
SlgLocalConfig.FloatingTextStyle =
{
    Normal      = 0,
    Skill       = 1,
    Critical    = 2,
    RedName     = 3,
    BlueName    = 4,
    Healing     = 5,
    SkillName   = 6,
    Status_Start = 7,
    Status_Win   = 8,
    Status_Fail  = 9,
    Durable     = 10,
}
---@type CS.UnityEngine.Vector3[]
SlgLocalConfig.DamageNumPos = {   
    [SlgLocalConfig.FloatingTextStyle.Normal  ] = CS.UnityEngine.Vector3( 0, 40, 0),
    [SlgLocalConfig.FloatingTextStyle.Skill   ] = CS.UnityEngine.Vector3( 0, 160, 0),
    [SlgLocalConfig.FloatingTextStyle.Critical] = CS.UnityEngine.Vector3( 0, 160, 0),
    [SlgLocalConfig.FloatingTextStyle.RedName ] = CS.UnityEngine.Vector3( 0, 40, 0),
    [SlgLocalConfig.FloatingTextStyle.BlueName] = CS.UnityEngine.Vector3( 0, 40, 0),
    [SlgLocalConfig.FloatingTextStyle.Healing ] = CS.UnityEngine.Vector3( 0, 40, 0),
    [SlgLocalConfig.FloatingTextStyle.SkillName ] = CS.UnityEngine.Vector3( 0, 100, 0),
    [SlgLocalConfig.FloatingTextStyle.Status_Start ] = CS.UnityEngine.Vector3( 0, 100, 0),
    [SlgLocalConfig.FloatingTextStyle.Status_Win   ] = CS.UnityEngine.Vector3( 0, 100, 0),
    [SlgLocalConfig.FloatingTextStyle.Status_Fail  ] = CS.UnityEngine.Vector3( 0, 100, 0),
    [SlgLocalConfig.FloatingTextStyle.Durable  ] = CS.UnityEngine.Vector3( 0, 40, 0),
}

SlgLocalConfig.BattleInfoPrefabPath = {
    'slg_floating_text_normal',             --    Normal      = 0, 
    'slg_floating_text_number',             --    Skill       = 1,
    'slg_floating_text_normal_critical',    --    Critical    = 2,
    'slg_floating_text_debuff',             --    RedName     = 3,
    'slg_floating_text_buff',               --    BlueName    = 4,
    'slg_floating_text_healing',            --    Healing     = 5,
    'slg_floating_text_skillname',          --    SkillName   = 6,
    'slg_troop_status_start',               --    Status_Start = 7,
    'slg_troop_status_win',                 --    Status_Win   = 8,
    'slg_troop_status_fail',                --    Status_Fail  = 9,
    'slg_floating_text_normal_city',        --    Durable        = 10,
}

SlgLocalConfig.FloatingTextOrthographicScale = 0.08
---@type number[]
SlgLocalConfig.FloatingTextLife = {   
    [SlgLocalConfig.FloatingTextStyle.Normal  ] = 0.9,
    [SlgLocalConfig.FloatingTextStyle.Skill   ] = 3,
    [SlgLocalConfig.FloatingTextStyle.Critical] = 3,
    [SlgLocalConfig.FloatingTextStyle.RedName ] = 3,
    [SlgLocalConfig.FloatingTextStyle.BlueName] = 3,
    [SlgLocalConfig.FloatingTextStyle.Healing ] = 3,
    [SlgLocalConfig.FloatingTextStyle.SkillName ] = 3,
    [SlgLocalConfig.FloatingTextStyle.Status_Start ] = 3,
    [SlgLocalConfig.FloatingTextStyle.Status_Win   ] = 3,
    [SlgLocalConfig.FloatingTextStyle.Status_Fail  ] = 3,
    [SlgLocalConfig.FloatingTextStyle.Durable  ] = 1.1,
}

SlgLocalConfig.TroopLyaerMask = 13
SlgLocalConfig.TroopLayer = 1 << SlgLocalConfig.TroopLyaerMask 
SlgLocalConfig.TroopMinLod = 0
SlgLocalConfig.TroopMaxLod = 1

SlgLocalConfig.MaxSoldierCount = {
    heigh = 11,
    low = 5
}

local ShapeType = require('ShapeType')
SlgLocalConfig.RangeVfxPath = {
    Imm = {
        [ShapeType.Rectangle] = 'vfx_s_range_box_imm',
        [ShapeType.Sector] = {
            [45] = 'vfx_s_range_45_imm',
            [90] = 'vfx_s_range_90_imm',
            [135] = 'vfx_s_range_135_imm',
            [180] = 'vfx_s_range_180_imm',        
        },
        [ShapeType.Round] = 'vfx_s_range_360_imm',
    },
    Chant = {[ShapeType.Rectangle] = 'vfx_s_range_box',
        [ShapeType.Sector] = {
            [45] = 'vfx_s_range_45',
            [90] = 'vfx_s_range_90',
            [135] = 'vfx_s_range_135',
            [180] = 'vfx_s_range_180',        
        },
        [ShapeType.Round] = 'vfx_s_range_360',
    }
}

return SlgLocalConfig