---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2023/6/23 19:53
---

local CityNPCUnloadLangContentVfxSchema = {
    {"textContent", typeof(CS.U2DTextMesh)}
}

return CityNPCUnloadLangContentVfxSchema