local CityProgressBarSchema = {
    {"root", typeof(CS.UnityEngine.Transform)},
    {"p_position", typeof(CS.UnityEngine.Transform)},
    {"icon", typeof(CS.U2DSpriteMesh)},
    {"sprite", typeof(CS.U2DSpriteMesh)},
    {"spriteB", typeof(CS.U2DSpriteMesh)},
    {"trigger", typeof(CS.DragonReborn.LuaBehaviour)},
    {"collider", typeof(CS.UnityEngine.BoxCollider)},
    {"time", typeof(CS.U2DTextMesh)},
    {"buffFlag", typeof(CS.UnityEngine.GameObject)},
    {"deBuffFlag", typeof(CS.UnityEngine.GameObject)},
    {"extraIconRoot", typeof(CS.UnityEngine.GameObject)},
    {"extraIcon1", typeof(CS.U2DSpriteMesh)},
    {"extraIcon2", typeof(CS.U2DSpriteMesh)},
    {"quantityText", typeof(CS.U2DTextMesh)},
    {"progress_root", typeof(CS.UnityEngine.GameObject)},
    {"progress_root_icon", typeof(CS.U2DSpriteMesh)},
    {"progress_action", typeof(CS.UnityEngine.GameObject)},
    {"citizen_status_icon", typeof(CS.U2DSpriteMesh)},
    {"pay_root", typeof(CS.UnityEngine.GameObject)},
    {"pay_trigger", typeof(CS.DragonReborn.LuaBehaviour)},
    {"pay_icon", typeof(CS.U2DSpriteMesh)},
    {"pay_num", typeof(CS.U2DTextMesh)},
    {"collect_effect", typeof(CS.UnityEngine.GameObject)},
    {"collect_effect_full", typeof(CS.UnityEngine.GameObject)},
    {"p_icon_pollution", typeof(CS.UnityEngine.GameObject)},
    {"p_icon_danger", typeof(CS.U2DSpriteMesh)},
    {"p_icon_creep", typeof(CS.U2DSpriteMesh)},
    {"facingCamera", typeof(CS.U2DFacingCamera)},
}

return CityProgressBarSchema
