---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2023/2/27 11:39
---
---@class CityFurnitureBuildingEntryBubbleSchema
local CityFurnitureBuildingEntryBubbleSchema = {
    {"p_text_num", typeof(CS.U2DTextMesh)},
    {"p_text_name", typeof(CS.U2DTextMesh)},
    {"p_building_click", typeof(CS.DragonReborn.LuaBehaviour)},
    {"p_npc_click", typeof(CS.DragonReborn.LuaBehaviour)},
    {"p_hint", typeof(CS.UnityEngine.GameObject)},
    {"p_icon_hint", typeof(CS.U2DSpriteMesh)},
    {"p_text_hint", typeof(CS.U2DTextMesh)},
    {"p_status", typeof(CS.StatusRecordParent)},
    {"p_text_goto", typeof(CS.U2DTextMesh)},
}

return CityFurnitureBuildingEntryBubbleSchema