---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shoufeng.zhang.
--- DateTime: 2022/6/1 16:16
---
local BaseTableViewProCell = require('BaseTableViewProCell')
local ConfigRefer = require('ConfigRefer')

---@class ItemGroupInfoCell : BaseTableViewProCell
---@field baseIcon BaseItemIcon
local ItemGroupInfoCell = class('ItemGroupInfoCell',BaseTableViewProCell)

function ItemGroupInfoCell:OnCreate(param)
    --override
    self:InitBind()
end

function ItemGroupInfoCell:InitBind()
    self.baseIcon = self:LuaObject('child_item_standard_s')
end

function ItemGroupInfoCell:OnOpened(param)
    --override
end

---OnFeedData
---@param data ItemGroupInfo
function ItemGroupInfoCell:OnFeedData(data)
    self:InitBind()
    if self.baseIcon then
        local itemCell = ConfigRefer.Item:Find(data:Items())
        if itemCell then
            self.baseIcon:FeedData(
                {
                    configCell = itemCell,
                    count = data:Nums(),
                    showTips = true
                }
            )
        end
    end
end
function ItemGroupInfoCell:OnClose(param)
    --override
end

function ItemGroupInfoCell:Select(param)
    --override
end
function ItemGroupInfoCell:UnSelect(param)
    --override
end
function ItemGroupInfoCell:OnRecycle(param)
    --override
end

function ItemGroupInfoCell:OnIconClick()

end

return ItemGroupInfoCell
