---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ericzhang.
--- DateTime: 2022/12/2 11:23
---

---@class CommonTipPopupDefine
local CommonTipPopupDefine = {}

---@class CommonTipPopupDefine.ArrowMode
CommonTipPopupDefine.ArrowMode = {
    Auto = 0,
    Up = 1,
    Down = 2,
    Left = 3,
    Right = 4,
}

return CommonTipPopupDefine