---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shoufeng.zhang.
--- DateTime: 2022/6/19 11:05
---
local ConfigRefer = require('ConfigRefer')
---@class HeroConfigCache
---@field New fun(config:HeroesConfigCell):HeroConfigCache
---@field HasHero fun(self:HeroConfigCache):boolean 是否获取英雄
---@field id number
---@field configCell HeroesConfigCell
---@field resCell HeroClientResConfigCell
---@field dbData wds.HeroInfo
---@field lv number
---@field star number
---@field isHide boolean
---@field heroInitParam wds.HeroInitParam
local HeroConfigCache = {}
local HeroConfigCache_mt = {}

---New
---@param config HeroesConfigCell
function HeroConfigCache.New(config)
    local o = {}
    setmetatable(o, {__index = HeroConfigCache_mt})
    o:Init(config)
    return o
end

---@param hero wds.HeroInitParam
---@param config HeroesConfigCell
function HeroConfigCache.FromHeroInitParam(hero, config)
    local o = {}
    setmetatable(o, {__index = HeroConfigCache_mt})
    o:Init(config)
    o.heroInitParam = hero
    return o
end

---Init
---@param config HeroesConfigCell
function HeroConfigCache_mt:Init(config)
    if not config then return end
    self.id = config:Id()
    self.configCell = config
    self.resCell = ConfigRefer.HeroClientRes:Find(config:ClientResCfg())
    self.dbData = nil
    self.isHide = config:Hide()
    self.heroInitParam = nil
end

---@return boolean
function HeroConfigCache_mt:HasHero()
    return self.dbData ~= nil
end

return HeroConfigCache