---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shoufeng.zhang.
--- DateTime: 2022/2/17 21:08
---
local PageBaseState = require('PageBaseState')
local QuestStateConstant = require('QuestStateConstant')
---@class PageState_PartNormal : PageBaseState
local PageState_PartNormal = class('PageState_PartNormal',PageBaseState)

function PageState_PartNormal:ctor(module,viewer,stateMachine)
    PageBaseState.ctor(self,module,viewer,stateMachine)
end

function PageState_PartNormal.GetName()
    return 'PageState_PartNormal'
end

function PageState_PartNormal:In()
    if self.viewer ~= nil then
        self.viewer:ShowPartNormalState()
    end
end


function PageState_PartNormal:Out()
    
end

function PageState_PartNormal:Next()
    -- local cmd = self.fsm:ReadBlackboard('cmd',true)
    -- if cmd == QuestStateConstant.StateCmd.QuestReward then
    --     return QuestStateConstant.StateName.QuestClaim
    -- elseif cmd == QuestStateConstant.StateCmd.PartReward then
    --     return QuestStateConstant.StateName.PartComplete
    -- end
    return QuestStateConstant.StateName.QuestClaim
end

function PageState_PartNormal:Refresh()
    if self.viewer ~= nil then
        self.viewer:ShowPartNormalState()
    end
end

return PageState_PartNormal